### ISSUE TITLE
The public workspace cannot be loaded on mobile devices

### ISSUE THREAD

**Issue by lawvs** [toeverything/AFFiNE#1694]
### What happened?

![photo](https://user-images.githubusercontent.com/18554747/227759442-2271d218-a5e9-4edf-88f4-d21fdd7de2b0.jpg)

### Version

app.affine.pro

### What browsers are you seeing the problem on?

Other

### Anything else?

If you use Chrome's developer tools to set the access as iPad, you will encounter a different error - the public workspace will be loading infinitely.

https://app.affine.pro/public-workspace/H6vffRmJbCfA-r3kq_36_

<img width="812" alt="Screenshot 2023-03-26 at 2 36 24 PM" src="https://user-images.githubusercontent.com/18554747/227759639-4a4e8d18-e269-4339-aa9c-1f5c36c4a8ec.png">

```
Error: val does not exist
    at s (_app-9f09f51c92cdc816.js:391:74833)
    at n.getChromeVersion (_app-9f09f51c92cdc816.js:267:223584)
    at h (_app-9f09f51c92cdc816.js:267:224806)
    at 19436 (_app-9f09f51c92cdc816.js:267:221148)
    at l (webpack-342ecdcf09d9b5cc.js:1:167)
    at 88712 (_app-9f09f51c92cdc816.js:267:181307)
    at l (webpack-342ecdcf09d9b5cc.js:1:167)
    at 6022 (_app-9f09f51c92cdc816.js:144:14474)
    at l (webpack-342ecdcf09d9b5cc.js:1:167)
    at 24338 (_app-9f09f51c92cdc816.js:144:13484)

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getInitialProps')
    at Object.<anonymous> (main-2fefe7cda33130a1.js:1:87628)
    at Generator.next (<anonymous>)
    at r (main-2fefe7cda33130a1.js:1:137)
    at l (main-2fefe7cda33130a1.js:1:334)
    at main-2fefe7cda33130a1.js:1:393
    at new Promise (<anonymous>)
    at Object.<anonymous> (main-2fefe7cda33130a1.js:1:275)
    at Object.c (main-2fefe7cda33130a1.js:1:87908)
    at Object.u [as loadGetInitialProps] (main-2fefe7cda33130a1.js:1:87531)
    at main-2fefe7cda33130a1.js:1:10833
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
reminder

https://app.affine.pro/public-workspace/H6vffRmJbCfA-r3kq_36_

keep '_'

**Comment by lawvs** [comment]
Related to https://github.com/toeverything/AFFiNE/commit/abdee7fac26862f6414ff0a82ae4958941253ed3

**Comment by Himself65** [comment]
fixed i think

**Comment by himself65** [comment]
I think this has been fixed in https://github.com/toeverything/AFFiNE/commit/abdee7fac26862f6414ff0a82ae4958941253ed3
