### ISSUE TITLE
Edgeless breaks for previous content

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#2427]
Using [0.0.0-20230518003659-684bbaf](https://github.com/toeverything/AFFiNE-Releases/releases/tag/0.0.0-20230518003659-684bbaf)

Any existing content can no longer transform into Edgeless.

![edgeless](https://github.com/toeverything/AFFiNE/assets/4605025/cd6765c5-27c1-4345-82fe-7b345381b367)

Console log:
```
app-cb0e62c418db0150.js:1758 Uncaught (in promise) Error: val does not exist
    at eh (_app-cb0e62c418db0150.js:1758:19824)
    at th._initSurface (280.a8b0ca1a3101fa8c.js:5123:21490)
    at th.update (280.a8b0ca1a3101fa8c.js:5123:26327)
    at th.performUpdate (_app-cb0e62c418db0150.js:1764:6489)
    at th.scheduleUpdate (_app-cb0e62c418db0150.js:1764:6126)
    at th._$Ej (_app-cb0e62c418db0150.js:1764:6032)
```

**Comment by xell** [comment]
Reopen as not being properly handled.
