### ISSUE TITLE
build failed on `@affine/native`

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3101]
```shell
➜  native git:(master) ✗ yarn build                    
   Compiling affine_native v0.0.0 (/Users/himself65/Code/AFFiNE/packages/native)
error: error returned from database: (code: 14) unable to open database file
  --> packages/native/src/sqlite/mod.rs:71:5
   |
71 | /     sqlx::query_as!(
72 | |       BlobRow,
73 | |       "INSERT INTO blobs (key, data) VALUES ($1, $2) ON CONFLICT(key) DO UPDATE SET data = excluded.data",
74 | |       key,
75 | |       blob,
76 | |     )
   | |_____^
   |
   = note: this error originates in the macro `$crate::sqlx_macros::expand_query` which comes from the expansion of the macro `sqlx::query_as` (in Nightly builds, run with -Z macro-backtrace for more info)

error: error returned from database: (code: 14) unable to open database file
  --> packages/native/src/sqlite/mod.rs:85:5
   |
85 | /     sqlx::query_as!(
86 | |       BlobRow,
87 | |       "SELECT key, data, timestamp FROM blobs WHERE key = ?",
88 | |       key
89 | |     )
   | |_____^
   |
   = note: this error originates in the macro `$crate::sqlx_macros::expand_query` which comes from the expansion of the macro `sqlx::query_as` (in Nightly builds, run with -Z macro-backtrace for more info)

error: error returned from database: (code: 14) unable to open database file
  --> packages/native/src/sqlite/mod.rs:97:5
   |
97 |     sqlx::query!("DELETE FROM blobs WHERE key = ?", key)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `$crate::sqlx_macros::expand_query` which comes from the expansion of the macro `sqlx::query` (in Nightly builds, run with -Z macro-backtrace for more info)

error: error returned from database: (code: 14) unable to open database file
   --> packages/native/src/sqlite/mod.rs:106:16
    |
106 |     let keys = sqlx::query!("SELECT key FROM blobs")
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` which comes from the expansion of the macro `sqlx::query` (in Nightly builds, run with -Z macro-backtrace for more info)

error: error returned from database: (code: 14) unable to open database file
   --> packages/native/src/sqlite/mod.rs:117:23
    |
117 |         Some(doc_id) => sqlx::query_as!(
    |  _______________________^
118 | |         UpdateRow,
119 | |         "SELECT id, timestamp, data, doc_id FROM updates WHERE doc_id = ?",
120 | |         doc_id
121 | |       )
    | |_______^
    |
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` which comes from the expansion of the macro `sqlx::query_as` (in Nightly builds, run with -Z macro-backtrace for more info)

error: error returned from database: (code: 14) unable to open database file
   --> packages/native/src/sqlite/mod.rs:125:15
    |
125 |         None => sqlx::query_as!(
    |  _______________^
126 | |         UpdateRow,
127 | |         "SELECT id, timestamp, data, doc_id FROM updates WHERE doc_id is NULL",
128 | |       )
    | |_______^
    |
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` which comes from the expansion of the macro `sqlx::query_as` (in Nightly builds, run with -Z macro-backtrace for more info)

error: error returned from database: (code: 14) unable to open database file
   --> packages/native/src/sqlite/mod.rs:140:9
    |
140 | /         sqlx::query!(
141 | |           "SELECT COUNT(*) as count FROM updates WHERE doc_id = ?",
142 | |           doc_id
143 | |         )
    | |_________^
    |
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` which comes from the expansion of the macro `sqlx::query` (in Nightly builds, run with -Z macro-backtrace for more info)

error: error returned from database: (code: 14) unable to open database file
   --> packages/native/src/sqlite/mod.rs:150:9
    |
150 |         sqlx::query!("SELECT COUNT(*) as count FROM updates WHERE doc_id is NULL")
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` which comes from the expansion of the macro `sqlx::query` (in Nightly builds, run with -Z macro-backtrace for more info)

error: error returned from database: (code: 14) unable to open database file
   --> packages/native/src/sqlite/mod.rs:162:19
    |
162 |     let updates = sqlx::query_as!(UpdateRow, "SELECT id, timestamp, data, doc_id FROM updates")
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` which comes from the expansion of the macro `sqlx::query_as` (in Nightly builds, run with -Z macro-backtrace for more info)

error: error returned from database: (code: 14) unable to open database file
   --> packages/native/src/sqlite/mod.rs:174:7
    |
174 | /       sqlx::query_as!(
175 | |         UpdateRow,
176 | |         "INSERT INTO updates (data, doc_id) VALUES ($1, $2)",
177 | |         update,
178 | |         doc_id
179 | |       )
    | |_______^
    |
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` which comes from the expansion of the macro `sqlx::query_as` (in Nightly builds, run with -Z macro-backtrace for more info)

error: error returned from database: (code: 14) unable to open database file
   --> packages/native/src/sqlite/mod.rs:197:23
    |
197 |       Some(doc_id) => sqlx::query!("DELETE FROM updates where doc_id = ?", doc_id)
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` which comes from the expansion of the macro `sqlx::query` (in Nightly builds, run with -Z macro-backtrace for more info)

error: error returned from database: (code: 14) unable to open database file
   --> packages/native/src/sqlite/mod.rs:201:15
    |
201 |       None => sqlx::query!("DELETE FROM updates where doc_id is NULL",)
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` which comes from the expansion of the macro `sqlx::query` (in Nightly builds, run with -Z macro-backtrace for more info)

error: error returned from database: (code: 14) unable to open database file
   --> packages/native/src/sqlite/mod.rs:209:7
    |
209 | /       sqlx::query_as!(
210 | |         UpdateRow,
211 | |         "INSERT INTO updates (data, doc_id) VALUES ($1, $2)",
212 | |         update,
213 | |         doc_id
214 | |       )
    | |_______^
    |
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` which comes from the expansion of the macro `sqlx::query_as` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `affine_native` (lib) due to 13 previous errors
Internal Error: Command failed: cargo build --release
    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at BuildCommand.<anonymous> (/Users/himself65/Code/AFFiNE/node_modules/@napi-rs/cli/scripts/index.js:11508:30)
    at Generator.next (<anonymous>)
    at /Users/himself65/Code/AFFiNE/node_modules/@napi-rs/cli/scripts/index.js:3512:71
    at new Promise (<anonymous>)
    at __awaiter$1 (/Users/himself65/Code/AFFiNE/node_modules/@napi-rs/cli/scripts/index.js:3508:12)
    at BuildCommand.execute (/Users/himself65/Code/AFFiNE/node_modules/@napi-rs/cli/scripts/index.js:11286:16)
    at BuildCommand.validateAndExecute (/Users/himself65/Code/AFFiNE/node_modules/@napi-rs/cli/scripts/index.js:2038:37)
➜  native git:(master) ✗ 

```

**Comment by himself65** [comment]
Fixed when I switch to rustc stable and clean the cache
