### ISSUE TITLE
Delete the last page in a workspace crashed​

### ISSUE THREAD

**Issue by teobler** [toeverything/AFFiNE#3412]
### What happened?

![bugs](https://github.com/toeverything/AFFiNE/assets/26424691/e619c4fd-0d7a-43a5-82a8-c2de911953c0)

### Distribution version

macOS x64 (Intel)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Relevant log output

```shell
Uncaught runtime errors:

ERROR
Cannot read properties of undefined (reading 'tags')
TypeError: Cannot read properties of undefined (reading 'tags')
  at get tags [as tags] (webpack-internal:///./node_modules/@blocksuite/blocks/dist/page-block/default/meta-data/meta-data.js:140:31)
  at PageMetaData.renderTagsInline (webpack-internal:///./node_modules/@blocksuite/blocks/dist/page-block/default/meta-data/meta-data.js:52:31)
  at PageMetaData.render (webpack-internal:///./node_modules/@blocksuite/blocks/dist/page-block/default/meta-data/meta-data.js:159:51)
  at PageMetaData.update (webpack-internal:///./node_modules/lit-element/development/lit-element.js:127:28)
  at PageMetaData.performUpdate (webpack-internal:///./node_modules/@lit/reactive-element/development/reactive-element.js:825:22)
  at PageMetaData.scheduleUpdate (webpack-internal:///./node_modules/@lit/reactive-element/development/reactive-element.js:760:21)
  at PageMetaData.__enqueueUpdate (webpack-internal:///./node_modules/@lit/reactive-element/development/reactive-element.js:733:29)
```

### Anything else?

After the last page be deleted, seems we do not set **currentPageId** to **null** 
`assertExists(pageMeta)` checking cannot pass in `BlockSuiteEditorHeader`

```
Uncaught runtime errors:

ERROR
val does not exist
  at assertExists (webpack-internal:///./node_modules/@blocksuite/global/dist/utils.js:37:15)
  at BlockSuiteEditorHeader (webpack-internal:///./apps/core/src/components/blocksuite/workspace-header/index.tsx:60:76)
  at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16305:18)
  at updateFunctionComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19583:20)
  at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21596:16)
  at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4164:14)
  at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4213:16)
  at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4277:31)
  at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27446:7)
  at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26552:12)
```

**but** if I set **currentPageId** to **null** , then I will get another error which shows in GIF. Seems BlockSuite wants to get some data from deleted page, cannot find the root cause by my poor context lol.

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!(I'd like to if there is more context can share with me)

**Comment by himself65** [comment]
I think the correct way is to jump to all page

**Comment by himself65** [comment]
```shell
Cannot read properties of undefined (reading 'tags')
TypeError: Cannot read properties of undefined (reading 'tags')
  at get tags [as tags] (webpack-internal:///./node_modules/@blocksuite/blocks/dist/page-block/default/meta-data/meta-data.js:140:31)
  at PageMetaData.renderTagsInline (webpack-internal:///./node_modules/@blocksuite/blocks/dist/page-block/default/meta-data/meta-data.js:52:31)
  at PageMetaData.render (webpack-internal:///./node_modules/@blocksuite/blocks/dist/page-block/default/meta-data/meta-data.js:159:51)
  at PageMetaData.update (webpack-internal:///./node_modules/lit-element/development/lit-element.js:127:28)
  at PageMetaData.performUpdate (webpack-internal:///./node_modules/@lit/reactive-element/development/reactive-element.js:825:22)
  at PageMetaData.scheduleUpdate (webpack-internal:///./node_modules/@lit/reactive-element/development/reactive-element.js:760:21)
  at PageMetaData.__enqueueUpdate (webpack-internal:///./node_modules/@lit/reactive-element/development/reactive-element.js:733:29)
```
