### ISSUE TITLE
Affine app keeps crashing

### ISSUE THREAD

**Issue by wassef** [toeverything/AFFiNE#4308]
### What happened?

I tried to import a workspace (.affine file) I saved from a Windows PC to an Arm64 Mac. This crashed the app instantly with the attached log error. 
I couldn't use the app anymore as it kept printing the same error message on restart.

### Distribution version

macOS ARM 64 (Apple Silicon)

### Relevant log output

```shell
Unexpected Application Error!
t.getMap is not a function
TypeError: t.getMap is not a function
  at B._handlePageIndexing (file://./js/npm-blocksuite-73c00eb6.js:16306:49442)
  at file://./js/npm-blocksuite-73c00eb6.js:16306:49056
  at Set.forEach (<anonymous>)
  at Array.<anonymous> (file://./js/npm-blocksuite-73c00eb6.js:16306:49007)
  at Object.es (file://./js/vendor-2dd301c2.js:21:171164)
  at tR (file://./js/vendor-2dd301c2.js:113:25771)
  at nh (file://./js/vendor-2dd301c2.js:113:51398)
  at nj._callObserver (file://./js/vendor-2dd301c2.js:113:58230)
  at Array.<anonymous> (file://./js/vendor-2dd301c2.js:113:35106)
  at es (file://./js/vendor-2dd301c2.js:21:171164)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Waiting for

https://github.com/toeverything/AFFiNE/commit/7b4e129602645151801d5d4f31e3233e422efa92

**Comment by Yuhang1015** [comment]
![image](https://github.com/toeverything/AFFiNE/assets/142964904/11dd2862-6c9c-46d1-b907-6eb1f59290f0)

Added a screenshot from Wssef.
