### ISSUE TITLE
404 error while checking for update on linux​

### ISSUE THREAD

**Issue by lucasadrianof** [toeverything/AFFiNE#4559]
### What happened?

Hey!

I'm currently using the [0.9.0-beta.1](https://github.com/toeverything/AFFiNE/releases/tag/0.9.0-beta.1) Linux .appimage release and I noticed a 404 error popup in my terminal every time I click on `Help > Check for updates`. Not sure if that's expected or not, so I thought about reporting it :)

This `latest-linux.yml` file doesn't seem to exist on that release's assets, which could explain the 404 error. 

I'm attaching the relevant logs below. 

### Distribution version

Linux

### Relevant log output

```shell
14:04:00.703 (main)   › [ipc-event] ui:onMaximized [ false ]
14:04:01.649 (main)   › [ipc-event] ui:onMaximized [ true ]
14:04:03.672 (main)   › Checking for update
14:04:03.672 (main)   › Checking for update
14:04:05.866 (main)   › Error: HttpError: 404 
"method: GET url: https://github.com/toeverything/AFFiNE/releases/download/0.9.0-beta.1/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": "no-cache",
  "content-encoding": "gzip",
  "content-length": "29",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-type": "text/plain; charset=utf-8",
  "date": "Wed, 04 Oct 2023 17:04:05 GMT",
  "referrer-policy": "no-referrer-when-downgrade",
  "server": "GitHub.com",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "x-content-type-options": "nosniff",
  "x-frame-options": "deny",
  "x-github-request-id": "8010:244BD:585BE:605F8:651D9B05",
  "x-xss-protection": "0"
}
    at createHttpError (/tmp/.mount_affineESRGQ4/usr/lib/affine-electron/resources/app/node_modules/builder-util-runtime/out/httpExecutor.js:14:12)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_affineESRGQ4/usr/lib/affine-electron/resources/app/node_modules/builder-util-runtime/out/httpExecutor.js:116:20)
    at ClientRequest.<anonymous> (/tmp/.mount_affineESRGQ4/usr/lib/affine-electron/resources/app/node_modules/builder-util-runtime/out/httpExecutor.js:82:26)
    at ClientRequest.emit (node:events:513:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49930)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joooye34** [comment]
https://github.com/toeverything/AFFiNE/releases/tag/0.9.0-beta.1 Seems no linux yaml file when releasing. @pengx17
