### ISSUE TITLE
​Unexpected error when upgrade to 0.10.0-canary.4

### ISSUE THREAD

**Issue by yestab123** [toeverything/AFFiNE#4778]
### What happened?

Unexpected Application Error!
Cannot read properties of undefined (reading 'byteLength')
TypeError: Cannot read properties of undefined (reading 'byteLength')
  at L (file://./js/chunk.npm-async-lodash-es-31492e53.js:1:8264)
  at tH (file://./js/chunk.npm-async-lodash-es-31492e53.js:1:13400)
  at t (file://./js/chunk.npm-async-lodash-es-31492e53.js:1:13718)
  at tJ (file://./js/chunk.npm-async-lodash-es-31492e53.js:1:13746)
  at i (file://./js/npm-jotai-2c660062.js:1:8384)
  at Object.read (file://./js/npm-jotai-2c660062.js:1:8506)
  at k (file://./js/npm-jotai-2c660062.js:1:3956)
  at file://./js/npm-jotai-2c660062.js:1:5026
  at Set.forEach (<anonymous>)
  at u (file://./js/npm-jotai-2c660062.js:1:4898)

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joooye34** [comment]
@yestab123 Thanks for your usage. We just release some big features, and we are fixing this fatal.

**Comment by joooye34** [comment]
@yestab123 We have release canary.5, if your app can't upgrade because of crash, you can download from here https://github.com/toeverything/AFFiNE/releases/tag/v0.10.0-canary.5.
