### ISSUE TITLE
Failure when page syncing

### ISSUE THREAD

**Issue by lawvs** [toeverything/AFFiNE#4980]
### What happened?

https://github.com/toeverything/AFFiNE/assets/18554747/bda12257-1363-43d1-a522-7a84254fbef8

### Distribution version

macOS x64 (Intel)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Relevant log output

```shell
slot.js:99 SyntaxError: "undefined" is not valid JSON
  at JSON.parse (<anonymous>)
  at r (xywh.js:5:17)
  at n.deserialize (bound.js:196:30)
  at Proxy.hitTest (note-model.js:62:29)
  at lJ.pickTopBlock (surface-block.js:399:23)
  at lJ.pickTop (surface-block.js:634:52)
  at df.getHoverState (tools-manager.js:344:33)
  at aI._refreshHoverRect (edgeless-hover-rect.js:18:52)
  at edgeless-hover-rect.js:42:78
  at slot.js:96:17

slot.js:99 [
  {
    "code": "invalid_type",
    "expected": "boolean",
    "received": "undefined",
    "path": [
      "isReverse"
    ],
    "message": "Required"
  }
]
  at new ed (https://prod.affineassets.com/87248b333/js/vendor-7b2977d0.js:172:24942)
  at get error [as error] (https://prod.affineassets.com/87248b333/js/vendor-7b2977d0.js:172:31394)
  at e2.parse (https://prod.affineassets.com/87248b333/js/vendor-7b2977d0.js:172:33560)
  at A.fromJSON (https://prod.affineassets.com/87248b333/js/npm-blocksuite-288bf3e4.js:1:19298)
  at H._jsonToSelection (https://prod.affineassets.com/87248b333/js/npm-blocksuite-288bf3e4.js:1:19798)
  at https://prod.affineassets.com/87248b333/js/npm-blocksuite-288bf3e4.js:1:21069
  at Array.map (<anonymous>)
  at https://prod.affineassets.com/87248b333/js/npm-blocksuite-288bf3e4.js:1:21057
  at Map.forEach (<anonymous>)
  at get remoteSelections [as remoteSelections] (https://prod.affineassets.com/87248b333/js/npm-blocksuite-288bf3e4.js:1:20978)
```
```


### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
Thank you! it seems you have fixed it in blocksuite, it should be merged into affine soon, let me close it first, if it is not fixed, please reopen it.
