### ISSUE TITLE
​check for update seem not work

### ISSUE THREAD

**Issue by TinsFox** [toeverything/AFFiNE#5378]
### What happened?

I am using Version 0.9.0-beta.2, and when I click on the check for updates, the log outputs `https://github.com/toeverything/AFFiNE/releases/download/v0.11.0-beta.4/latest-mac.yml`

### Distribution version

macOS ARM 64 (Apple Silicon)

### Relevant log output

```shell
[2023-12-22 11:00:16.875] [info]  (main)   Checking for update
[2023-12-22 11:00:16.877] [info]  (main)   Checking for update
[2023-12-22 11:00:17.650] [error] (main)   Error: HttpError: 404 
"method: GET url: https://github.com/toeverything/AFFiNE/releases/download/v0.11.0-beta.4/latest-mac.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": "no-cache",
  "content-encoding": "gzip",
  "content-length": "29",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-type": "text/plain; charset=utf-8",
  "date": "Fri, 22 Dec 2023 02:59:15 GMT",
  "referrer-policy": "no-referrer-when-downgrade",
  "server": "GitHub.com",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "x-content-type-options": "nosniff",
  "x-frame-options": "deny",
  "x-github-request-id": "9C48:11A14B:2C626C:2FE1DB:6584FBC1",
  "x-xss-protection": "0"
}
    at createHttpError (/Applications/AFFiNE-beta.app/Contents/Resources/app/node_modules/builder-util-runtime/out/httpExecutor.js:14:12)
    at ElectronHttpExecutor.handleResponse (/Applications/AFFiNE-beta.app/Contents/Resources/app/node_modules/builder-util-runtime/out/httpExecutor.js:116:20)
    at ClientRequest.<anonymous> (/Applications/AFFiNE-beta.app/Contents/Resources/app/node_modules/builder-util-runtime/out/httpExecutor.js:82:26)
    at ClientRequest.emit (node:events:513:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49930)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
[2023-12-22 11:00:17.652] [error] (main)   Error while updating client HttpError: 404 
"method: GET url: https://github.com/toeverything/AFFiNE/releases/download/v0.11.0-beta.4/latest-mac.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": "no-cache",
  "content-encoding": "gzip",
  "content-length": "29",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-type": "text/plain; charset=utf-8",
  "date": "Fri, 22 Dec 2023 02:59:15 GMT",
  "referrer-policy": "no-referrer-when-downgrade",
  "server": "GitHub.com",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "x-content-type-options": "nosniff",
  "x-frame-options": "deny",
  "x-github-request-id": "9C48:11A14B:2C626C:2FE1DB:6584FBC1",
  "x-xss-protection": "0"
}
    at createHttpError (/Applications/AFFiNE-beta.app/Contents/Resources/app/node_modules/builder-util-runtime/out/httpExecutor.js:14:12)
    at ElectronHttpExecutor.handleResponse (/Applications/AFFiNE-beta.app/Contents/Resources/app/node_modules/builder-util-runtime/out/httpExecutor.js:116:20)
    at ClientRequest.<anonymous> (/Applications/AFFiNE-beta.app/Contents/Resources/app/node_modules/builder-util-runtime/out/httpExecutor.js:82:26)
    at ClientRequest.emit (node:events:513:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49930)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joooye34** [comment]
Hello @TinsFox , I will check this. We improve the release flow last iteration. Maybe have a problem here. The beta.5 is available at https://github.com/toeverything/AFFiNE/releases/tag/v0.11.0-beta.5, you can download it here if necessary.
