### ISSUE TITLE
Cloud log in not working​

### ISSUE THREAD

**Issue by Cossackx** [toeverything/AFFiNE#5598]
### What happened?

Error loading into cloud web based...

Unexpected Application Error!
Loading chunk 7554 failed. (error: https://prod.affineassets.com/0a0ee37ac/js/chunk.7554-3728f558.js)
ChunkLoadError: Loading chunk 7554 failed.
(error: https://prod.affineassets.com/0a0ee37ac/js/chunk.7554-3728f558.js)
    at t.f.j (https://prod.affineassets.com/0a0ee37ac/js/runtime-1e693b32.js:1:9195)
    at https://prod.affineassets.com/0a0ee37ac/js/runtime-1e693b32.js:1:2673
    at Array.reduce (<anonymous>)
    at t.e (https://prod.affineassets.com/0a0ee37ac/js/runtime-1e693b32.js:1:2652)
    at Object.lazy (https://prod.affineassets.com/0a0ee37ac/js/app-f7435788.js:1:69106)
    at X (https://prod.affineassets.com/0a0ee37ac/js/vendor-b0406079.js:10:30959)
    at K (https://prod.affineassets.com/0a0ee37ac/js/vendor-b0406079.js:10:31763)
    at https://prod.affineassets.com/0a0ee37ac/js/vendor-b0406079.js:10:21240
    at Array.map (<anonymous>)
    at eP (https://prod.affineassets.com/0a0ee37ac/js/vendor-b0406079.js:10:21233)
    at eO (https://prod.affineassets.com/0a0ee37ac/js/vendor-b0406079.js:10:17321)
    at eI (https://prod.affineassets.com/0a0ee37ac/js/vendor-b0406079.js:10:15437)
    at Object.eC [as navigate] (https://prod.affineassets.com/0a0ee37ac/js/vendor-b0406079.js:10:14192)
    at https://prod.affineassets.com/0a0ee37ac/js/vendor-b0406079.js:72:1195
    at https://prod.affineassets.com/0a0ee37ac/js/chunk.8830-02f8ef20.js:1:2290
    at https://prod.affineassets.com/0a0ee37ac/js/chunk.8830-02f8ef20.js:1:2848
    at https://prod.affineassets.com/0a0ee37ac/js/chunk.4470-bad02d4d.js:1:1702
    at uI (https://prod.affineassets.com/0a0ee37ac/js/npm-react-0adf682d.js:9:84110)
    at uY (https://prod.affineassets.com/0a0ee37ac/js/npm-react-0adf682d.js:9:90490)
    at e (https://prod.affineassets.com/0a0ee37ac/js/npm-react-0adf682d.js:9:111083)
    at https://prod.affineassets.com/0a0ee37ac/js/npm-react-0adf682d.js:9:111094
    at oI (https://prod.affineassets.com/0a0ee37ac/js/npm-react-0adf682d.js:9:111606)
    at oS (https://prod.affineassets.com/0a0ee37ac/js/npm-react-0adf682d.js:9:94978)
    at E (https://prod.affineassets.com/0a0ee37ac/js/npm-react-0adf682d.js:33:1364)
    at MessagePort.T (https://prod.affineassets.com/0a0ee37ac/js/npm-react-0adf682d.js:33:1894)

### Distribution version

Web (app.affine.pro)

### Relevant log output

```shell
Unexpected Application Error!
Loading chunk 7554 failed. (error: https://prod.affineassets.com/0a0ee37ac/js/chunk.7554-3728f558.js)
ChunkLoadError: Loading chunk 7554 failed.
(error: https://prod.affineassets.com/0a0ee37ac/js/chunk.7554-3728f558.js)
    at t.f.j (https://prod.affineassets.com/0a0ee37ac/js/runtime-1e693b32.js:1:9195)
    at https://prod.affineassets.com/0a0ee37ac/js/runtime-1e693b32.js:1:2673
    at Array.reduce (<anonymous>)
    at t.e (https://prod.affineassets.com/0a0ee37ac/js/runtime-1e693b32.js:1:2652)
    at Object.lazy (https://prod.affineassets.com/0a0ee37ac/js/app-f7435788.js:1:69106)
    at X (https://prod.affineassets.com/0a0ee37ac/js/vendor-b0406079.js:10:30959)
    at K (https://prod.affineassets.com/0a0ee37ac/js/vendor-b0406079.js:10:31763)
    at https://prod.affineassets.com/0a0ee37ac/js/vendor-b0406079.js:10:21240
    at Array.map (<anonymous>)
    at eP (https://prod.affineassets.com/0a0ee37ac/js/vendor-b0406079.js:10:21233)
    at eO (https://prod.affineassets.com/0a0ee37ac/js/vendor-b0406079.js:10:17321)
    at eI (https://prod.affineassets.com/0a0ee37ac/js/vendor-b0406079.js:10:15437)
    at Object.eC [as navigate] (https://prod.affineassets.com/0a0ee37ac/js/vendor-b0406079.js:10:14192)
    at https://prod.affineassets.com/0a0ee37ac/js/vendor-b0406079.js:72:1195
    at https://prod.affineassets.com/0a0ee37ac/js/chunk.8830-02f8ef20.js:1:2290
    at https://prod.affineassets.com/0a0ee37ac/js/chunk.8830-02f8ef20.js:1:2848
    at https://prod.affineassets.com/0a0ee37ac/js/chunk.4470-bad02d4d.js:1:1702
    at uI (https://prod.affineassets.com/0a0ee37ac/js/npm-react-0adf682d.js:9:84110)
    at uY (https://prod.affineassets.com/0a0ee37ac/js/npm-react-0adf682d.js:9:90490)
    at e (https://prod.affineassets.com/0a0ee37ac/js/npm-react-0adf682d.js:9:111083)
    at https://prod.affineassets.com/0a0ee37ac/js/npm-react-0adf682d.js:9:111094
    at oI (https://prod.affineassets.com/0a0ee37ac/js/npm-react-0adf682d.js:9:111606)
    at oS (https://prod.affineassets.com/0a0ee37ac/js/npm-react-0adf682d.js:9:94978)
    at E (https://prod.affineassets.com/0a0ee37ac/js/npm-react-0adf682d.js:33:1364)
    at MessagePort.T (https://prod.affineassets.com/0a0ee37ac/js/npm-react-0adf682d.js:33:1894)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
It seems to be a network problem, please try refreshing the page.
