### ISSUE TITLE
Unexpected Application Error! Unknown workspace flavour: affine​

### ISSUE THREAD

**Issue by PrinOrange** [toeverything/AFFiNE#5899]
### What happened?

When I login with my Google Account it jumps to such error page.
![image](https://github.com/toeverything/AFFiNE/assets/73331790/565b3095-88ac-43f2-b470-26f2a1c929ab)

And when I turn to the router `https://app.affine.pro/workspace/`, it indicates me that I have no power to visit the Workspace page
![image](https://github.com/toeverything/AFFiNE/assets/73331790/14cb3cd7-1983-468b-8343-dcc989be416c)

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Microsoft Edge

### Relevant log output

```shell
Unexpected Application Error!
Unknown workspace flavour: affine
Error: Unknown workspace flavour: affine
    at R.open (https://prod.affineassets.com/js/app-1268d2d3.js:1:34266)
    at R.use (https://prod.affineassets.com/js/app-1268d2d3.js:1:33261)
    at https://prod.affineassets.com/js/chunk.7657-7d8c1cd3.js:1:8028
    at uI (https://prod.affineassets.com/js/npm-react-a490e7b3.js:9:84110)
    at oU (https://prod.affineassets.com/js/npm-react-a490e7b3.js:9:113154)
    at o (https://prod.affineassets.com/js/npm-react-a490e7b3.js:9:107707)
    at E (https://prod.affineassets.com/js/npm-react-a490e7b3.js:33:1364)
    at MessagePort.T (https://prod.affineassets.com/js/npm-react-a490e7b3.js:33:1894)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
It seems that you may have used affine very early and left some dirty data. Try clearing all data in the browser app.affine.pro and try again.



![Image](https://github.com/toeverything/AFFiNE/assets/13579374/0c94c87a-da80-48fe-9285-242cbded2e61)
