### ISSUE TITLE
All docs page crashed

### ISSUE THREAD

**Issue by lawvs** [toeverything/AFFiNE#6320]
### What happened?

<img width="1177" alt="Screenshot 2024-03-26 at 16 11 23" src="https://github.com/toeverything/AFFiNE/assets/18554747/389d1c8a-50da-4410-8507-648b247f82a5">

### Distribution version

macOS x64 (Intel)

AFFiNE Beta
0.14.0-beta.0

Editor Version
0.14.0-canary-202403250855-4171ecd

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Relevant log output

<img width="901" alt="Screenshot 2024-03-26 at 16 14 06" src="https://github.com/toeverything/AFFiNE/assets/18554747/e9f005d0-2404-4b28-9e54-d11bc43a1016">

```shell

vendor-2c542e81.js:37 Error: The livedata is poisoned, original error: Error: The livedata is poisoned, original error: TypeError: Cannot read properties of undefined (reading 'includes')
    at app-c475d067.js:46:518210
    at Array.filter (<anonymous>)
    at app-c475d067.js:46:518185
    at a (app-c475d067.js:3:9664)
```

### Anything else?

https://github.com/toeverything/AFFiNE/blob/669ca325a1d9a9081a29f0a0c50ac2b3306b74e4/packages/frontend/core/src/modules/tag/entities/tag.ts#L67-L72

**Comment by lawvs** [comment]
Fixed in https://github.com/toeverything/AFFiNE/pull/6321
