### ISSUE TITLE
Can't start docker container​

### ISSUE THREAD

**Issue by supersourix** [toeverything/AFFiNE#6411]
### What happened?

Can't start docker compose container.
Running from local compose.yaml, as your docs gave the same error.

Let me know if you need more info.

```
OS: Debian GNU/Linux 12 (bookworm) x86_64 
Kernel: 6.1.0-18-amd64 
Uptime: 4 days, 8 mins 
Packages: 579 (dpkg) 
Shell: bash 5.2.15 
Terminal: /dev/pts/5
CPU: Intel i7-6700HQ (8) @ 3.500GHz 
GPU: NVIDIA GeForce GTX 1070 Mobile 
Memory: 1157MiB / 7746MiB
```

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Firefox

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
user@Server:~/Containers/affine$ sudo docker compose up
[+] Running 3/0
 ✔ Container affine_postgres    Created                                                                                                                                                          0.0s 
 ✔ Container affine_redis       Created                                                                                                                                                          0.0s 
 ✔ Container affine_selfhosted  Recreated                                                                                                                                                        0.1s 
Attaching to affine_postgres, affine_redis, affine_selfhosted
affine_redis       | 1:C 29 Mar 2024 19:49:55.171 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
affine_redis       | 1:C 29 Mar 2024 19:49:55.172 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
affine_redis       | 1:C 29 Mar 2024 19:49:55.172 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
affine_redis       | 1:C 29 Mar 2024 19:49:55.172 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
affine_redis       | 1:M 29 Mar 2024 19:49:55.173 * monotonic clock: POSIX clock_gettime
affine_redis       | 1:M 29 Mar 2024 19:49:55.173 * Running mode=standalone, port=6379.
affine_redis       | 1:M 29 Mar 2024 19:49:55.174 * Server initialized
affine_redis       | 1:M 29 Mar 2024 19:49:55.174 * Loading RDB produced by version 7.2.4
affine_redis       | 1:M 29 Mar 2024 19:49:55.174 * RDB age 1047 seconds
affine_redis       | 1:M 29 Mar 2024 19:49:55.174 * RDB memory usage when created 0.85 Mb
affine_redis       | 1:M 29 Mar 2024 19:49:55.174 * Done loading RDB, keys loaded: 1, keys expired: 0.
affine_redis       | 1:M 29 Mar 2024 19:49:55.174 * DB loaded from disk: 0.000 seconds
affine_redis       | 1:M 29 Mar 2024 19:49:55.174 * Ready to accept connections tcp
affine_postgres    | 
affine_postgres    | PostgreSQL Database directory appears to contain a database; Skipping initialization
affine_postgres    | 
affine_postgres    | 2024-03-29 19:49:55.325 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
affine_postgres    | 2024-03-29 19:49:55.325 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
affine_postgres    | 2024-03-29 19:49:55.325 UTC [1] LOG:  listening on IPv6 address "::", port 5432
affine_postgres    | 2024-03-29 19:49:55.331 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
affine_postgres    | 2024-03-29 19:49:55.340 UTC [29] LOG:  database system was shut down at 2024-03-29 19:32:21 UTC
affine_postgres    | 2024-03-29 19:49:55.347 UTC [1] LOG:  database system is ready to accept connections
affine_selfhosted  | running predeploy script.
affine_selfhosted  | yarn run v1.22.19
affine_selfhosted  | $ yarn prisma migrate deploy && node --import ./scripts/register.js ./dist/data/index.js run
affine_selfhosted  | $ /app/node_modules/.bin/prisma migrate deploy
affine_selfhosted  | Error: request to https://binaries.prisma.sh/all_commits/5a9203d0590c951969e85a7d07215503f4672eb9/debian-openssl-3.0.x/libquery_engine.so.node.gz.sha256 failed, reason: getaddrinfo EAI_AGAIN binaries.prisma.sh
affine_selfhosted  | error Command failed with exit code 1.
affine_selfhosted  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
affine_selfhosted  | error Command failed with exit code 1.
affine_selfhosted  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
affine_selfhosted  | node:internal/errors:984
affine_selfhosted  |   const err = new Error(message);
affine_selfhosted  |               ^
affine_selfhosted  | 
affine_selfhosted  | Error: Command failed: yarn predeploy
affine_selfhosted  |     at genericNodeError (node:internal/errors:984:15)
affine_selfhosted  |     at wrappedFn (node:internal/errors:538:14)
affine_selfhosted  |     at checkExecSyncError (node:child_process:890:11)
affine_selfhosted  |     at execSync (node:child_process:962:15)
affine_selfhosted  |     at runPredeployScript (file:///app/scripts/self-host-predeploy.js:67:3)
affine_selfhosted  |     at file:///app/scripts/self-host-predeploy.js:75:1
affine_selfhosted  |     at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
affine_selfhosted  |     at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
affine_selfhosted  |     at async loadESM (node:internal/process/esm_loader:28:7)
affine_selfhosted  |     at async handleMainPromise (node:internal/modules/run_main:113:12) {
affine_selfhosted  |   status: 1,
affine_selfhosted  |   signal: null,
affine_selfhosted  |   output: [ null, null, null ],
affine_selfhosted  |   pid: 20,
affine_selfhosted  |   stdout: null,
affine_selfhosted  |   stderr: null
affine_selfhosted  | }
affine_selfhosted  | 
affine_selfhosted  | Node.js v20.12.0
affine_selfhosted exited with code 0
```

**Comment by EYHN** [comment]
It seems that there is an error connecting to binaries.prisma.sh . Please make sure your environment has an internet connection. (at least on first boot)
