### ISSUE TITLE
​Error when click the uprade button about Price Plan on my self-host Affine

### ISSUE THREAD

**Issue by syuim** [toeverything/AFFiNE#6440]
### What happened?

​Error when click the uprade button about Price Plan on my self-host Affine

![image](https://github.com/toeverything/AFFiNE/assets/18261192/920ff22c-fe81-4f4d-8903-083842597a82)

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
affine_selfhosted | [Nest] 132 - 04/02/2024, 5:47:19 AM ERROR [GQLLoggerPlugin] GraphQL Unhandled Error
affine_selfhosted | GraphQLError: Cannot query field "prices" on type "Query".
affine_selfhosted | at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)
affine_selfhosted | at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
affine_selfhosted | at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
affine_selfhosted | at visit (/app/node_modules/graphql/language/visitor.js:197:21)
affine_selfhosted | at validate (/app/node_modules/graphql/validation/validate.js:91:24)
affine_selfhosted | at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
affine_selfhosted | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
affine_selfhosted | at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:635:16)
affine_selfhosted | at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
affine_selfhosted | at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
```

**Comment by CatsJuice** [comment]
Payment is not available in self-host version for now. Feel free to reopen if you have other questions.
