### ISSUE TITLE
Error during build: Failed to open git repo in AFFiNE-canary

### ISSUE THREAD

**Issue by mirtaqi07** [toeverything/AFFiNE#6497]
### What happened?

yarn install was run successfully. But after that when I do yarn dev in root dir, it gives the following error. I tried but couldn't figure out. Kindly help! 

THANKS!

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

### Relevant log output

```shell
PS F:\AFFiNE-canary> yarn dev
(node:11520) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm/transpile-only.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11520) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
│
◇  Distribution
│  browser
│
◇  Mode
│  development
│
◇  Channel
│  canary
│
◇  Enable coverage
│  No
│
◇  Debug blocksuite locally?
│  No
{
  distribution: 'browser',
  mode: 'development',
  channel: 'canary',
  coverage: false,
  localBlockSuite: undefined,
  entry: undefined
}
No extname found for WRka6R7pvS4AKqYQRl5aBeIkQqLGkNOpB_iVroJQKtc=
No extname found for NuuYD2-GljLA2H_qI0-ipdeB7YHgwkn_e05G--V8F6M=
No extname found for pmPMoebd5Z2h2cblWB_TxEw4C5VKdVc0r4BDzMu5Jrw=
No extname found for 4KbnQ1P38nUux0Tf2fdGqc909fVzGz8PJVuvuSVvnzc=
No extname found for jnpiF-qH-9NYu1WEx_asdmPfIBVf_Y5AX64yq-Jvbic=
No extname found for YuPd_NI22xNMhfm3GHSonetlA9pebkl-z1fsocwM638=
No extname found for JwGgaM_IRE2A9RLtMk8KKbyHAz1rQ3SxnCmNt5CI0Q4=
No extname found for GZ_5Nfi_yOnFdewbiXaHBimUOI7RxeVR10AY_R9seUs=
No extname found for YUo3S6WvBWTO3fcRR1iUKLXVFxnILmP-VTwdM3ai-h0=
No extname found for lrxxmLPiDeoDlEDUuBQp51JXetfPiG7l7HUzuKzDKuo=
No extname found for bj5CO1PAn9WoCcikLfC-I7y1meYfcQYGiH4ssS73wBM=
No extname found for drvxbiVuSxmtX2JHqbsR28u-irFo2y7FetDWdSofGBQ=
No extname found for pfRNuE2FYppI-IZnJj28Vbj7wAJraa6cPtlz-xDgqgk=
No extname found for 4O1wLjFf9P0VHP1Gou2jNtqNzfV5BCaUqN1rOxjkl_A=
No extname found for OBZvFNxrfRCCrUvwgt9tsIx0dbBOwz2NIahP3OgpwHE=
No extname found for efvD5QWAVJ2fi3xSQuns2JMLudwvpJxAUcSGPLtCvv8=
No extname found for drvxbiVuSxmtX2JHqbsR28u-irFo2y7FetDWdSofGBQ=
No extname found for WHCOR8R09TJ7Awru1kxZBvb3A7aAZdNN2JvUkW0P_VY=
No extname found for bj5CO1PAn9WoCcikLfC-I7y1meYfcQYGiH4ssS73wBM=
build flags {
  distribution: 'browser',
  mode: 'development',
  channel: 'canary',
  coverage: false,
  localBlockSuite: undefined,
  entry: undefined
}
runtime config {
  isSelfHosted: false,
  enableTestProperties: true,
  enableBroadcastChannelProvider: true,
  enableDebugPage: true,
  githubUrl: 'https://github.com/toeverything/AFFiNE',
  changelogUrl: 'https://github.com/toeverything/AFFiNE/releases',
  downloadUrl: 'https://affine.pro/download',
  imageProxyUrl: '/api/worker/image-proxy',
  linkPreviewUrl: '/api/worker/link-preview',
  enablePreloading: true,
  enableNewSettingModal: true,
  enableNewSettingUnstableApi: false,
  enableSQLiteProvider: true,
  enableMoveDatabase: false,
  enableCloud: true,
  enableCaptcha: false,
  enableEnhanceShareMode: false,
  enablePayment: true,
  enablePageHistory: true,
  allowLocalWorkspace: true,
  serverUrlPrefix: 'http://localhost:8080',
  appVersion: '0.14.0',
  editorVersion: '0.14.0-canary-202403250855-4171ecd',
  appBuildType: 'canary'
}
Error during build: Error: Failed to open git repo: [F:\AFFiNE-canary], reason: could not find repository at 'F:\AFFiNE-canary'; class=Repository (6); code=NotFound (-3)
    at file:///F:/AFFiNE-canary/tools/cli/src/webpack/webpack.config.ts:15:18
    at file:///F:/AFFiNE-canary/node_modules/lodash-es/before.js:31:21
    at createWebpackConfig (file:///F:/AFFiNE-canary/tools/cli/src/webpack/webpack.config.ts:43:36)
    at file:///F:/AFFiNE-canary/tools/cli/src/bin/dev.ts:118:20 {
  code: 'GenericFailure'
}
PS F:\AFFiNE-canary>
```

**Comment by CatsJuice** [comment]
I guess you didn't download the repository via `git clone`, but directly downloaded the **zip** from GitHub. You can redownload via **git clone** or init your `F:/AFFiNE-canary/` as git repository and set remote origin.

**Comment by mirtaqi07** [comment]
Yes, you're right. `git clone` was giving me fetch-error. I switched the network, now the issue is fixed. Thanks bro!
