### ISSUE TITLE
self-host: read only public link does not work

### ISSUE THREAD

**Issue by alissa-tung** [toeverything/AFFiNE#6868]
### What happened?

read only public link can not be opened

** incognito mode does not have such issue**

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
Mixpanel is not initialized, calling identify with args: ["some-of-my-hidden-uuid"]
index.ts:83 i18n init success
mixpanel.ts:20 Mixpanel is not initialized, calling track_pageview with args: [{"page":"/share/my-url","appVersion":"0.15.0-beta.0","environment":"beta","editorVersion":"0.14.0-canary-202405070525-ad1cc9f","isSelfHosted":true}]
share-detail-page.tsx:181 Error: Doc record not found
    at tm.open (docs.ts:25:13)
    at share-detail-page.tsx:171:58
(anonymous)	@	share-detail-page.tsx:181
```

**Comment by alissa-tung** [comment]
open in incognito mode does not have such issue
