### ISSUE TITLE
​URI malformed reported by WsExceptionHandler

### ISSUE THREAD

**Issue by Energetic6877** [toeverything/AFFiNE#6927]
### What happened?

In the frontend, the website is empty except for a frozen "syncing..." status. The backend logs show a URI malformed error during a call to decodeURIComponent

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
ERROR [WsExceptionsHandler] URI malformed
app-1  | URIError: URI malformed
app-1  |     at decodeURIComponent (<anonymous>)
app-1  |     at file:///app/dist/fundamentals/utils/request.js:28:31
app-1  |     at Array.reduce (<anonymous>)
app-1  |     at getRequestResponseFromHost (file:///app/dist/fundamentals/utils/request.js:24:52)
app-1  |     at getRequestResponseFromContext (file:///app/dist/fundamentals/utils/request.js:50:12)
app-1  |     at AuthGuard.canActivate (file:///app/dist/core/auth/guard.js:29:30)
app-1  |     at GuardsConsumer.tryActivate (/app/node_modules/@nestjs/core/guards/guards-consumer.js:15:34)
app-1  |     at canActivateFn (/app/node_modules/@nestjs/websockets/context/ws-context-creator.js:63:59)
app-1  |     at /app/node_modules/@nestjs/websockets/context/ws-context-creator.js:51:37
app-1  |     at EventsGateway.<anonymous> (/app/node_modules/@nestjs/websockets/context/ws-proxy.js:12:38)
```

### Anything else?

![Screenshot from 2024-05-14 10-23-40](https://github.com/toeverything/AFFiNE/assets/167532037/2c1a2b18-391a-4c27-8e01-6351862e9483)
(I have cut out the workspace image)

**Comment by erikboberg** [comment]
I have the exact same issue.
