### ISSUE TITLE
Self-hosted affine(table-412b919) cannot start properly.

### ISSUE THREAD

**Issue by zoverdoser** [toeverything/AFFiNE#7139]
### What happened?

The container affine_selfhosted keeps restarting. The affine web goes 503 Service Unavailable

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
affine_selfhosted  | [Nest] 92  - 06/04/2024, 7:01:35 AM   ERROR [RunCommand] Failed to run data migration
affine_selfhosted  | [Nest] 92  - 06/04/2024, 7:01:35 AM   ERROR [RunCommand] Error: Feature administrator not found
affine_selfhosted  | error Command failed with exit code 1.
affine_selfhosted  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
affine_selfhosted  | node:internal/errors:984
affine_selfhosted  |   const err = new Error(message);
affine_selfhosted  |               ^
affine_selfhosted  | 
affine_selfhosted  | Error: Command failed: yarn predeploy
affine_selfhosted  |     at genericNodeError (node:internal/errors:984:15)
affine_selfhosted  |     at wrappedFn (node:internal/errors:538:14)
affine_selfhosted  |     at checkExecSyncError (node:child_process:890:11)
affine_selfhosted  |     at execSync (node:child_process:962:15)
affine_selfhosted  |     at runPredeployScript (file:///app/scripts/self-host-predeploy.js:67:3)
affine_selfhosted  |     at file:///app/scripts/self-host-predeploy.js:75:1
affine_selfhosted  |     at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
affine_selfhosted  |     at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
affine_selfhosted  |     at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
affine_selfhosted  |   status: 1,
affine_selfhosted  |   signal: null,
affine_selfhosted  |   output: [ null, null, null ],
affine_selfhosted  |   pid: 20,
affine_selfhosted  |   stdout: null,
affine_selfhosted  |   stderr: null
affine_selfhosted  | }
affine_selfhosted  | 
affine_selfhosted  | Node.js v20.14.0
affine_selfhosted  | running predeploy script.
affine_selfhosted  | yarn run v1.22.22
affine_selfhosted  | $ yarn prisma migrate deploy && node --import ./scripts/register.js ./dist/data/index.js run
affine_selfhosted  | $ /app/node_modules/.bin/prisma migrate deploy
affine_redis       | 1:C 04 Jun 2024 06:57:23.328 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
affine_redis       | 1:C 04 Jun 2024 06:57:23.334 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
affine_redis       | 1:C 04 Jun 2024 06:57:23.334 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
affine_redis       | 1:C 04 Jun 2024 06:57:23.334 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
affine_redis       | 1:M 04 Jun 2024 06:57:23.335 * monotonic clock: POSIX clock_gettime
affine_redis       | 1:M 04 Jun 2024 06:57:23.335 * Running mode=standalone, port=6379.
affine_redis       | 1:M 04 Jun 2024 06:57:23.338 * Server initialized
affine_redis       | 1:M 04 Jun 2024 06:57:23.344 * Loading RDB produced by version 7.2.4
affine_redis       | 1:M 04 Jun 2024 06:57:23.345 * RDB age 1417 seconds
affine_redis       | 1:M 04 Jun 2024 06:57:23.345 * RDB memory usage when created 0.86 Mb
affine_redis       | 1:M 04 Jun 2024 06:57:23.345 * Done loading RDB, keys loaded: 1, keys expired: 0.
affine_redis       | 1:M 04 Jun 2024 06:57:23.349 * DB loaded from disk: 0.010 seconds
affine_redis       | 1:M 04 Jun 2024 06:57:23.349 * Ready to accept connections tcp
affine_postgres    | 
affine_postgres    | PostgreSQL Database directory appears to contain a database; Skipping initialization
affine_postgres    | 
affine_postgres    | 2024-06-04 06:57:24.257 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
affine_postgres    | 2024-06-04 06:57:24.260 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
affine_postgres    | 2024-06-04 06:57:24.260 UTC [1] LOG:  listening on IPv6 address "::", port 5432
affine_postgres    | 2024-06-04 06:57:24.272 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
affine_postgres    | 2024-06-04 06:57:24.300 UTC [29] LOG:  database system was shut down at 2024-06-04 06:33:46 UTC
affine_postgres    | 2024-06-04 06:57:24.370 UTC [1] LOG:  database system is ready to accept connections
affine_postgres    | 2024-06-04 06:59:30.371 UTC [128] LOG:  could not receive data from client: Connection reset by peer
affine_selfhosted  | Prisma schema loaded from schema.prisma
affine_selfhosted  | Datasource "db": PostgreSQL database "affine", schema "public" at "postgres:5432"
affine_selfhosted  | 
affine_selfhosted  | 33 migrations found in prisma/migrations
affine_selfhosted  | 
affine_selfhosted  | 
affine_selfhosted  | No pending migrations to apply.
affine_selfhosted  | (node:91) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
affine_selfhosted  | (Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by elisaday** [comment]
+1, but different logs.

```
affine  | running predeploy script.
affine  | yarn run v1.22.22
affine  | $ yarn prisma migrate deploy && node --import ./scripts/register.js ./dist/data/index.js run
affine  | $ /app/node_modules/.bin/prisma migrate deploy
affine  | Prisma schema loaded from schema.prisma
affine  | Datasource "db": PostgreSQL database "affine", schema "public" at "localhost:5432"
affine  |
affine  | 33 migrations found in prisma/migrations
affine  |
affine  |
affine  | No pending migrations to apply.
affine  | (node:95) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
affine  | (Use `node --trace-warnings ...` to show where the warning was created)
affine  | file:///app/dist/config/affine.js:88
affine  | AFFiNE.plugins.use('redis', {
affine  |                ^
affine  |
affine  | TypeError: AFFiNE.plugins.use is not a function
affine  |     at file:///app/dist/config/affine.js:88:16
affine  |     at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
affine  |     at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
affine  |     at async loadRemote (file:///app/dist/prelude.js:16:5)
affine  |     at async load (file:///app/dist/prelude.js:37:5)
affine  |     at async file:///app/dist/prelude.js:46:1
affine  |
affine  | Node.js v20.14.0
affine  | error Command failed with exit code 1.
affine  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
affine  | node:internal/errors:984
affine  |   const err = new Error(message);
affine  |               ^
affine  |
affine  | Error: Command failed: yarn predeploy
affine  |     at genericNodeError (node:internal/errors:984:15)
affine  |     at wrappedFn (node:internal/errors:538:14)
affine  |     at checkExecSyncError (node:child_process:890:11)
affine  |     at execSync (node:child_process:962:15)
affine  |     at runPredeployScript (file:///app/scripts/self-host-predeploy.js:67:3)
affine  |     at file:///app/scripts/self-host-predeploy.js:75:1
affine  |     at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
affine  |     at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
affine  |     at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
affine  |   status: 1,
affine  |   signal: null,
affine  |   output: [ null, null, null ],
affine  |   pid: 20,
affine  |   stdout: null,
affine  |   stderr: null
affine  | }
affine  |
affine  | Node.js v20.14.0
```

**Comment by forehalo** [comment]
@elisaday the solution is mentioned in #6708

and it looks like a breaking change compared to a very old config system. we will figure out a better way to smoothly migrate user configuration if you are not that hurry
