### ISSUE TITLE
Data got lost after update affine self-hosted stable-01fc1ea​

### ISSUE THREAD

**Issue by zoverdoser** [toeverything/AFFiNE#7148]
### What happened?

Lost all the workspaces when I login after I updated to stable-01fc1ea​. My account looks like a brand new user.

### Distribution version

Linux

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
affine_postgres    | 
affine_postgres    | PostgreSQL Database directory appears to contain a database; Skipping initialization
affine_postgres    | 
affine_postgres    | 2024-06-04 11:28:41.687 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
affine_postgres    | 2024-06-04 11:28:41.688 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
affine_postgres    | 2024-06-04 11:28:41.689 UTC [1] LOG:  listening on IPv6 address "::", port 5432
affine_postgres    | 2024-06-04 11:28:41.701 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
affine_postgres    | 2024-06-04 11:28:41.734 UTC [29] LOG:  database system was shut down at 2024-06-04 07:28:01 UTC
affine_postgres    | 2024-06-04 11:28:41.806 UTC [1] LOG:  database system is ready to accept connections
affine_postgres    | 2024-06-04 11:33:41.833 UTC [27] LOG:  checkpoint starting: time
affine_postgres    | 2024-06-04 11:33:50.371 UTC [27] LOG:  checkpoint complete: wrote 87 buffers (0.5%); 0 WAL file(s) added, 0 removed, 0 recycled; write=8.473 s, sync=0.051 s, total=8.538 s; sync files=56, longest=0.008 s, average=0.001 s; distance=409 kB, estimate=409 kB; lsn=0/2FFD990, redo lsn=0/2FF9F10
affine_redis       | 1:C 04 Jun 2024 11:28:39.817 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
affine_redis       | 1:C 04 Jun 2024 11:28:39.819 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
affine_redis       | 1:C 04 Jun 2024 11:28:39.819 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
affine_redis       | 1:C 04 Jun 2024 11:28:39.819 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
affine_redis       | 1:M 04 Jun 2024 11:28:39.822 * monotonic clock: POSIX clock_gettime
affine_redis       | 1:M 04 Jun 2024 11:28:39.824 * Running mode=standalone, port=6379.
affine_redis       | 1:M 04 Jun 2024 11:28:39.833 * Server initialized
affine_redis       | 1:M 04 Jun 2024 11:28:39.837 * Loading RDB produced by version 7.2.4
affine_redis       | 1:M 04 Jun 2024 11:28:39.837 * RDB age 14438 seconds
affine_redis       | 1:M 04 Jun 2024 11:28:39.837 * RDB memory usage when created 0.85 Mb
affine_redis       | 1:M 04 Jun 2024 11:28:39.837 * Done loading RDB, keys loaded: 1, keys expired: 0.
affine_redis       | 1:M 04 Jun 2024 11:28:39.846 * DB loaded from disk: 0.013 seconds
affine_redis       | 1:M 04 Jun 2024 11:28:39.846 * Ready to accept connections tcp
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] MailerModule dependencies initialized +0ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] StorageProviderModule dependencies initialized +1ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] HelpersModule dependencies initialized +0ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] ServeStaticModule dependencies initialized +4ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +2ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] MailModule dependencies initialized +1ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] StorageModule dependencies initialized +0ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] ServerConfigModule dependencies initialized +3ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] ThrottlerModule dependencies initialized +2ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] RateLimiterModule dependencies initialized +3ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] GraphQLSchemaBuilderModule dependencies initialized +2ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] QuotaModule dependencies initialized +3ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] FeatureModule dependencies initialized +1ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] DocModule dependencies initialized +1ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] EventsModule dependencies initialized +2ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] UserModule dependencies initialized +3ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] GraphQLModule dependencies initialized +3ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] AuthModule dependencies initialized +3ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [InstanceLoader] WorkspaceModule dependencies initialized +3ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [WebSocketsController] EventsGateway subscribed to the "client-handshake-sync" message +82ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [WebSocketsController] EventsGateway subscribed to the "client-handshake-awareness" message +1ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [WebSocketsController] EventsGateway subscribed to the "client-leave-sync" message +3ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [WebSocketsController] EventsGateway subscribed to the "client-leave-awareness" message +3ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [WebSocketsController] EventsGateway subscribed to the "client-pre-sync" message +1ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [WebSocketsController] EventsGateway subscribed to the "client-update-v2" message +1ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [WebSocketsController] EventsGateway subscribed to the "doc-load-v2" message +0ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [WebSocketsController] EventsGateway subscribed to the "awareness-init" message +0ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [WebSocketsController] EventsGateway subscribed to the "awareness-update" message +1ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [RoutesResolver] AuthController {/api/auth}: +10ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [RouterExplorer] Mapped {/api/auth/sign-in, POST} route +15ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [RouterExplorer] Mapped {/api/auth/sign-out, GET} route +17ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [RouterExplorer] Mapped {/api/auth/magic-link, POST} route +1ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [RouterExplorer] Mapped {/api/auth/session, GET} route +1ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [RouterExplorer] Mapped {/api/auth/sessions, GET} route +5ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [RouterExplorer] Mapped {/api/auth/challenge, GET} route +6ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [RoutesResolver] UserAvatarController {/api/avatars}: +2ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [RouterExplorer] Mapped {/api/avatars/:id, GET} route +2ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [RoutesResolver] WorkspacesController {/api/workspaces}: +3ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [RouterExplorer] Mapped {/api/workspaces/:id/blobs/:name, GET} route +4ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [RouterExplorer] Mapped {/api/workspaces/:id/docs/:guid, GET} route +3ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [RouterExplorer] Mapped {/api/workspaces/:id/docs/:guid/histories/:timestamp, GET} route +4ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [DocManager] Use Database
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:45 AM     LOG [DocManager] Automation started
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:46 AM     LOG [GraphQLModule] Mapped {/graphql, POST} route +1122ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:46 AM     LOG [NestApplication] Nest application successfully started +393ms
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:46 AM     LOG [App] AFFiNE Server is running in [selfhosted] mode
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:46 AM     LOG [App] Listening on http://0.0.0.0:3010
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:30:46 AM     LOG [App] And the public server should be recognized as http://localhost:3010
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:13 AM VERBOSE [CacheInterceptor] cache blobs:0357fe7d-2584-44a3-9b41-04031ec09041 miss
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:13 AM VERBOSE [CacheInterceptor] cache blobs:0357fe7d-2584-44a3-9b41-04031ec09041 staled
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:13 AM   DEBUG [DocManager] pushed 1 updates for 0357fe7d-2584-44a3-9b41-04031ec09041 in workspace 0357fe7d-2584-44a3-9b41-04031ec09041
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:13 AM VERBOSE [FsStorageProvider:blobs] Object `0357fe7d-2584-44a3-9b41-04031ec09041/BFZk3c2ERp-sliRvA7MQ_p3NdkdCLt2Ze0DQ9i21dpA=` put
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:13 AM   DEBUG [DocManager] pushed 1 updates for uwt7GKieBf64K_Pf8IbWO in workspace 0357fe7d-2584-44a3-9b41-04031ec09041
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:14 AM VERBOSE [CacheInterceptor] cache blobs:0357fe7d-2584-44a3-9b41-04031ec09041 staled
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:14 AM   DEBUG [DocManager] Squashed 1 updates for 0357fe7d-2584-44a3-9b41-04031ec09041 in workspace 0357fe7d-2584-44a3-9b41-04031ec09041
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:14 AM VERBOSE [FsStorageProvider:blobs] Object `0357fe7d-2584-44a3-9b41-04031ec09041/HWvCItS78DzPGbwcuaGcfkpVDUvL98IvH5SIK8-AcL8=` put
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:14 AM VERBOSE [CacheInterceptor] cache blobs:0357fe7d-2584-44a3-9b41-04031ec09041 staled
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:14 AM VERBOSE [FsStorageProvider:blobs] Object `0357fe7d-2584-44a3-9b41-04031ec09041/ZRKpsBoC88qEMmeiXKXqywfA1rLvWoLa5rpEh9x9Oj0=` put
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:14 AM   DEBUG [DocManager] Squashed 1 updates for uwt7GKieBf64K_Pf8IbWO in workspace 0357fe7d-2584-44a3-9b41-04031ec09041
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:15 AM   DEBUG [DocManager] pushed 1 updates for 0357fe7d-2584-44a3-9b41-04031ec09041 in workspace 0357fe7d-2584-44a3-9b41-04031ec09041
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:15 AM   DEBUG [DocManager] Squashed 1 updates for 0357fe7d-2584-44a3-9b41-04031ec09041 in workspace 0357fe7d-2584-44a3-9b41-04031ec09041
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:15 AM   DEBUG [DocHistoryManager] History created for 0357fe7d-2584-44a3-9b41-04031ec09041 in workspace 0357fe7d-2584-44a3-9b41-04031ec09041.
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:18 AM   DEBUG [DocManager] pushed 1 updates for uwt7GKieBf64K_Pf8IbWO in workspace 0357fe7d-2584-44a3-9b41-04031ec09041
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:19 AM   DEBUG [DocManager] Squashed 1 updates for uwt7GKieBf64K_Pf8IbWO in workspace 0357fe7d-2584-44a3-9b41-04031ec09041
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:19 AM   DEBUG [DocHistoryManager] History created for uwt7GKieBf64K_Pf8IbWO in workspace 0357fe7d-2584-44a3-9b41-04031ec09041.
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:40 AM   ERROR [WsExceptionsHandler] You are not signed in.
affine_selfhosted  | UnauthorizedException: You are not signed in.
affine_selfhosted  |     at AuthGuard.canActivate (file:///app/dist/core/auth/guard.js:53:19)
affine_selfhosted  |     at GuardsConsumer.tryActivate (/app/node_modules/@nestjs/core/guards/guards-consumer.js:15:34)
affine_selfhosted  |     at canActivateFn (/app/node_modules/@nestjs/websockets/context/ws-context-creator.js:63:59)
affine_selfhosted  |     at /app/node_modules/@nestjs/websockets/context/ws-context-creator.js:51:37
affine_selfhosted  |     at EventsGateway.<anonymous> (/app/node_modules/@nestjs/websockets/context/ws-proxy.js:12:38)
affine_selfhosted  |     at /app/node_modules/@nestjs/platform-socket.io/adapters/io-adapter.js:36:34
affine_selfhosted  |     at doInnerSub (/app/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:22:31)
affine_selfhosted  |     at outerNext (/app/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:17:70)
affine_selfhosted  |     at OperatorSubscriber._this._next (/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
affine_selfhosted  |     at Subscriber.next (/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:40 AM   ERROR [WsExceptionsHandler] You are not signed in.
affine_selfhosted  | UnauthorizedException: You are not signed in.
affine_selfhosted  |     at AuthGuard.canActivate (file:///app/dist/core/auth/guard.js:53:19)
affine_selfhosted  |     at GuardsConsumer.tryActivate (/app/node_modules/@nestjs/core/guards/guards-consumer.js:15:34)
affine_selfhosted  |     at canActivateFn (/app/node_modules/@nestjs/websockets/context/ws-context-creator.js:63:59)
affine_selfhosted  |     at /app/node_modules/@nestjs/websockets/context/ws-context-creator.js:51:37
affine_selfhosted  |     at EventsGateway.<anonymous> (/app/node_modules/@nestjs/websockets/context/ws-proxy.js:12:38)
affine_selfhosted  |     at /app/node_modules/@nestjs/platform-socket.io/adapters/io-adapter.js:36:34
affine_selfhosted  |     at doInnerSub (/app/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:22:31)
affine_selfhosted  |     at outerNext (/app/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:17:70)
affine_selfhosted  |     at OperatorSubscriber._this._next (/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
affine_selfhosted  |     at Subscriber.next (/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:33:50 AM VERBOSE [CacheInterceptor] cache blobs:0357fe7d-2584-44a3-9b41-04031ec09041 miss
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:34:15 AM VERBOSE [CacheInterceptor] cache blobs:0357fe7d-2584-44a3-9b41-04031ec09041 hit
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:34:51 AM VERBOSE [CacheInterceptor] cache blobs:0357fe7d-2584-44a3-9b41-04031ec09041 hit
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:35:16 AM VERBOSE [CacheInterceptor] cache blobs:0357fe7d-2584-44a3-9b41-04031ec09041 hit
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:35:52 AM VERBOSE [CacheInterceptor] cache blobs:0357fe7d-2584-44a3-9b41-04031ec09041 hit
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:35:54 AM VERBOSE [CacheInterceptor] cache blobs:0357fe7d-2584-44a3-9b41-04031ec09041 hit
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:36:55 AM VERBOSE [CacheInterceptor] cache blobs:0357fe7d-2584-44a3-9b41-04031ec09041 hit
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:37:56 AM VERBOSE [CacheInterceptor] cache blobs:0357fe7d-2584-44a3-9b41-04031ec09041 hit
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:38:57 AM VERBOSE [CacheInterceptor] cache blobs:0357fe7d-2584-44a3-9b41-04031ec09041 hit
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:39:58 AM VERBOSE [CacheInterceptor] cache blobs:0357fe7d-2584-44a3-9b41-04031ec09041 hit
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:40:59 AM VERBOSE [CacheInterceptor] cache blobs:0357fe7d-2584-44a3-9b41-04031ec09041 hit
affine_selfhosted  | [Nest] 110  - 06/04/2024, 11:42:00 AM VERBOSE [CacheInterceptor] cache blobs:0357fe7d-2584-44a3-9b41-04031ec09041 hit
```

### Anything else?

I rolled back to the last workable stable version, but my data isn't there either. How can I get my data back?

**Comment by LIHAQ** [comment]
Me too

**Comment by forehalo** [comment]
first of all, the data won't be touched at all during the upgrading

you could run `yarn prisma studio` in your container and expose port `5555` to host server, to check is the data there, especially the `User`, `Snapshot` tables

**Comment by zoverdoser** [comment]
@forehalo  How to restore my data to affine?

**Comment by forehalo** [comment]
> @forehalo How to restore my data to affine?

make sure you signed in the correct account which owns the workspace that you said "lost". the records in `User` table may help

**Comment by LIHAQ** [comment]
> > @forehalo How to restore my data to affine?
> 
> make sure you signed in the correct account which owns the workspace that you said "lost". the records in `User` table may help

@forehalo @zoverdoser 
I looked at the snapshot using yarn prisma studio
![image](https://github.com/toeverything/AFFiNE/assets/57976650/a25e4d72-986f-4c19-bb25-fabdb0df72ae)
A workspace was indeed added today
![image](https://github.com/toeverything/AFFiNE/assets/57976650/ed836232-a601-4dcd-9005-8f776c39cabf)
Finally, I adjusted the workspace permission in the WorkspaceUserPermission, selected the original workspace, and returned to normal
![image](https://github.com/toeverything/AFFiNE/assets/57976650/ad8c8892-061b-4a85-b910-320af3e79a0d)

**Comment by zoverdoser** [comment]
> > @forehalo How to restore my data to affine?
> 
> make sure you signed in the correct account which owns the workspace that you said "lost". the records in `User` table may help

I'm sure I signed in the correct account. There are 2 users  in the records in `User` table, which I created before. But the create time of my account has been updated. Looks like a new account had been created and replaced my account.
![a7ada8ff3057c1d4ee66b7e60954631](https://github.com/toeverything/AFFiNE/assets/863481/4a67c02d-2786-4153-aa19-a8728eadd771)

**Comment by LIHAQ** [comment]
> > > @forehalo How to restore my data to affine?
> > 
> > 
> > make sure you signed in the correct account which owns the workspace that you said "lost". the records in `User` table may help
> 
> I'm sure I signed in the correct account. There are 2 users in the records in `User` table, which I created before. But the create time of my account has been updated. Looks like a new account had been created and replaced my account. ![a7ada8ff3057c1d4ee66b7e60954631](https://private-user-images.githubusercontent.com/863481/336671401-4a67c02d-2786-4153-aa19-a8728eadd771.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NTcxMjUsIm5iZiI6MTcxNzU1NjgyNSwicGF0aCI6Ii84NjM0ODEvMzM2NjcxNDAxLTRhNjdjMDJkLTI3ODYtNDE1My1hYTE5LWE4NzI4ZWFkZDc3MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQwMzA3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTQ4NzRkNjMzYmVlOGMzYmUwYzQzM2QzMzU3NDU1Y2MwZDk3NjUxYzc0ZjYyYmMxODNmMGRiYmI1YzFmMDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HETNiciFkGF4_CHtzFFIzRubM7Uf5_0y6-LYTzBBRGM)

@zoverdoser 
I'm a new user like you
![image](https://github.com/toeverything/AFFiNE/assets/57976650/7965d02e-7e88-448f-a312-3b7d371b7d58)
you can try to select the specified user and owned workspace in the WorkspaceUserPermission, and you should be able to resume work
![image](https://github.com/toeverything/AFFiNE/assets/57976650/02710df9-742b-40b2-a732-29b531d878de)

**Comment by zoverdoser** [comment]
@LIHAQ All the 'user's value in the WorkspaceUserPermission are set to my account. But my workspaces still don't show up in my affine.
![80b4817923e4b962a32be60df27a609](https://github.com/toeverything/AFFiNE/assets/863481/1826fb7b-20f8-4948-bdab-2806e8f3eaa2)

**Comment by LIHAQ** [comment]
> @LIHAQ All the 'user's value in the WorkspaceUserPermission are set to my account. But my workspaces still don't show up in my affine. ![80b4817923e4b962a32be60df27a609](https://private-user-images.githubusercontent.com/863481/336676261-1826fb7b-20f8-4948-bdab-2806e8f3eaa2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NTkzNzAsIm5iZiI6MTcxNzU1OTA3MCwicGF0aCI6Ii84NjM0ODEvMzM2Njc2MjYxLTE4MjZmYjdiLTIwZjgtNDk0OC1iZGFiLTI4MDZlOGYzZWFhMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQwMzQ0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWMwYTAyZTI1ZjExNDBjY2FkMTAyMDQ1NzY2MjYxOWU1MWI3MjQ4YjU3ZGNlZTU0YjgzYzRmMjlhYjYyM2U0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yNegktMwruem2H41p4CYC-0tUQeL0XWgBJ7YdYA55Rk)

First, check whether the original workspace exists
![image](https://github.com/toeverything/AFFiNE/assets/57976650/af3ccc47-8c9b-4098-96c2-4a66a1545e79)
If so, check the User and workspace in the WorkspaceUserPermission, respectively
![image](https://github.com/toeverything/AFFiNE/assets/57976650/ca03fed4-de12-47d0-a99c-5e73d8c0739e)
If not, then I can't help much here, because it is different from the problem I encountered.

**Comment by zoverdoser** [comment]
@LIHAQ  The original workspaces exist. 
![image](https://github.com/toeverything/AFFiNE/assets/863481/1c7deff5-46ca-4568-b0b2-12a5e95a23e4)
But I logged in to my affine, and found this.
![image](https://github.com/toeverything/AFFiNE/assets/863481/2b3c683f-a9ee-4b99-93bb-4bf5b9303a12)

**Comment by forehalo** [comment]
> @LIHAQ The original workspaces exist. ![image](https://private-user-images.githubusercontent.com/863481/336681438-1c7deff5-46ca-4568-b0b2-12a5e95a23e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjAzMjMsIm5iZiI6MTcxNzU2MDAyMywicGF0aCI6Ii84NjM0ODEvMzM2NjgxNDM4LTFjN2RlZmY1LTQ2Y2EtNDU2OC1iMGIyLTEyYTVlOTVhMjNlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQwNDAwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmM1MTVkMjZiZjgwMzA3YmQ5MTk1MzAwYTVjNTJmMThmYWQzZmNlNjMwMDdjZDJlNjk2NTI1YTJkY2MyMzE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KebJOlyrNWxp-7oKkeYzSQKH7cQNoyAAXFXTSBrdHyk) But I logged in to my affine, and found this. ![image](https://private-user-images.githubusercontent.com/863481/336681668-2b3c683f-a9ee-4b99-93bb-4bf5b9303a12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjAzMjMsIm5iZiI6MTcxNzU2MDAyMywicGF0aCI6Ii84NjM0ODEvMzM2NjgxNjY4LTJiM2M2ODNmLWE5ZWUtNGI5OS05M2JiLTRiZjViOTMwM2ExMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQwNDAwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWYxNGU2MDE1MGFkYWMyNjJlOTE5ODg5YTQyNmMzOTA3ZTFmYTE3NWQ4ZTcyMmNlZjAyNmIzZDZlZDAyNTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q9MfbEOLd554JnxLxP7zIdnl4TMZ6BLHE64zg7sfbpE)

there should be one record with type `99` in `WorkspaceUserPermission` table for each workspace

for example

// User table

|id|email|
|-|-|
|user a| admin@you.com|

// Workspace table

|id|
|-|
|workspace a|

// WorkspaceUserPermission table

|id|workspaceId|userId|type|
|-|-|-|-|
|p1|workspace a|user a|99|

**Comment by zoverdoser** [comment]
@forehalo This works. I manually added some records and got back my workspaces. Type 10 should be workspace members.

**Comment by forehalo** [comment]
good to hear it! I will double check the upgrading logic to avoid such condition later on
