### ISSUE TITLE
[AI Function] Unable to read AI conversation history records already in the database

### ISSUE THREAD

**Issue by emengweb** [toeverything/AFFiNE#7515]
### What happened?

When using the AI ​​function, the server log reports an error, and it seems that the corresponding data in the database cannot be found.
This problem resulted in the inability to read the AI ​​conversation history records already in the database.
Checked the _prisma_migrations table and the latest migrations have been executed: 20240708034904_prompt_level_config

```
ERROR [GraphQL] Internal server error
PrismaClientKnownRequestError: 
Invalid `prisma.aiSession.findMany()` invocation:
The column `t3.attachments` does not exist in the current database.
    at _n.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6927)
    at _n.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6235)
    at _n.request (/app/node_modules/@prisma/client/runtime/library.js:122:5919)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:131:9116)
    at async ChatSessionService.listHistories (file:///app/dist/plugins/copilot/session.js:302:16)
    at async CopilotResolver.histories (file:///app/dist/plugins/copilot/resolver.js:375:27)
    at async target (/app/node_modules/@nestjs/core/helpers/external-context-creator.js:74:28)
```
and this error
```
ERROR [Sse] Internal server error
PrismaClientKnownRequestError: 
Invalid `prisma.aiSessionMessage.createMany()` invocation:
The column `params` does not exist in the current database.
    at _n.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6927)
    at _n.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6235)
    at _n.request (/app/node_modules/@prisma/client/runtime/library.js:122:5919)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:131:9116)
    at async file:///app/dist/plugins/copilot/session.js:171:21
    at async Proxy._transactionWithCallback (/app/node_modules/@prisma/client/runtime/library.js:131:7483)
    at async ChatSessionService.setSession (file:///app/dist/plugins/copilot/session.js:141:16)
    at async ChatSession.dispose (file:///app/dist/plugins/copilot/session.js:507:17)
    at async ChatSession.save (file:///app/dist/plugins/copilot/session.js:120:9)
```

The following is the database structure:
```
# ai_sessions_metadata
character varying(36) |  
character varying(36) |  
character varying(36) |  
character varying(36) |  
character varying(32) |  
timestamptz(6) [CURRENT_TIMESTAMP] |  
timestamptz(6) NULL |  
integer [0] |  
integer [0] |  
character varying(36) NULL

# ai_sessions_messages
character varying(36) |  
character varying(36) |  
"AiPromptRole" |  
text |  
timestamptz(6) [CURRENT_TIMESTAMP] |  
timestamptz(6)

```

Hope the cause of the problem can be located and solved.

### Distribution version

Linux

### Are you self-hosting?

- [X] Yes

**Comment by emengweb** [comment]
I manually ran the last few AI-related SQLs in the migrations directory and the problem was solved.
