### ISSUE TITLE
无法复制,复制时控制台显示报错​

### ISSUE THREAD

**Issue by SAnBlog** [toeverything/AFFiNE#7520]
### What happened?

在文档中复制时控制台显示报错,无法使用复制功能

### Distribution version

macOS x64 (Intel)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [x] Yes

### Relevant log output

TypeError: Cannot read properties of undefined (reading 'write')
    at n.writeToClipboard (index.ts:281:31)
    at async n.copySlice (index.ts:109:5)

**Comment by SAnBlog** [comment]
使用https正常,本地或者局域网没有ssl协议则无法复制
