### ISSUE TITLE
​Feature Request: Custom OpenAI URL Environment Variable

### ISSUE THREAD

**Issue by martin0359** [toeverything/AFFiNE#7705]
### Description

# Feature Request: Custom OpenAI URL Environment Variable

## Description
We propose adding support for a custom OpenAI URL through an environment variable in the AFFiNE Copilot plugin. This feature would allow users to specify an alternative endpoint for OpenAI API calls, which is particularly useful for users in regions with restricted access to the default OpenAI servers.

## Motivation
Users in certain geographical locations, such as China, often face difficulties accessing OpenAI's servers directly due to network restrictions. By allowing a custom URL to be set, users can utilize proxy services or alternative endpoints to maintain functionality of the Copilot feature.

## Proposed Implementation
1. Add a new environment variable, e.g., `AFFINE_OPENAI_API_URL`.
2. Modify the Copilot plugin to check for this environment variable.
3. If the variable is set, use its value as the base URL for OpenAI API calls instead of the default URL.

## Configuration Example
In the AFFiNE configuration file or environment:

```javascript
AFFiNE.use('copilot', {
  openai: {
    apiKey: 'your-key',
    apiUrl: process.env.AFFINE_OPENAI_API_URL || 'https://api.openai.com', // Default URL if not set
  },
  // ... other configurations
})

### Use case

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
FYI, we are testing through all over the AI functionalities, and once it's done, together with the release of admin panel, it will be easier to switch OpenAI api endpoint and api key.

**Comment by Aliang-code** [comment]
It is hoped that the specified models can be supported at the same time

**Comment by martin0359** [comment]
> FYI, we are testing through all over the AI functionalities, and once it's done, together with the release of admin panel, it will be easier to switch OpenAI api endpoint and api key.

How long will it take, now that I can't live without Affine, can I customize the transit url?

**Comment by DiazMichael** [comment]
> It is hoped that the specified models can be supported at the same time

@Aliang-code Does this mean models outside of the OpenAI ones? Meaning, could I have my own suite of local LLMs as long as I have an OpenAI compatible server?

**Comment by Aliang-code** [comment]
> > It is hoped that the specified models can be supported at the same time
> 
> @Aliang-code Does this mean models outside of the OpenAI ones? Meaning, could I have my own suite of local LLMs as long as I have an OpenAI compatible server?

yes that's what we need

**Comment by OiAnthony** [comment]
link: https://github.com/toeverything/AFFiNE/discussions/7030

**Comment by v3ss0n** [comment]
Is this never going to implemented? it is just a config variable away to let us use our own AI. We use affine because it is opensource and selfhostable. Gatekeeping AI to AffineAI would defeat this purpose.

**Comment by Traxmaxx** [comment]
@v3ss0n you can already configure your own OpenAI compatible backend with
```
openai: {
  apiKey: 'xyz',
  baseURL: 'https://myollamainstance.tld/api/v1',
},
```

just make sure you have the required models configured, see https://github.com/toeverything/AFFiNE/discussions/7030#discussioncomment-10041242

**Comment by CytecLove** [comment]
@Traxmaxx 

Affine 0.18.2

AFFiNE.use('copilot', {
openai: {
baseURL: 'http://myip:11434/v1/',
apiKey:'ollama'
},
fal: {
apiKey: 'null',
},
unsplashKey: 'null',
storage: {
provider: 'cloudflare-r2',
bucket: 'copilot',
}
})

I am trying to use ollama instead of text gen webui but i keep running into an error
affine_server | [Nest] 1 - 12/17/2024, 7:51:41 AM ERROR [GraphQL] Internal server error
affine_server | GraphQLError: Cannot query field "createCopilotSession" on type "Mutation".
affine_server | at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)
affine_server | at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
affine_server | at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
affine_server | at visit (/app/node_modules/graphql/language/visitor.js:197:21)
affine_server | at validate (/app/node_modules/graphql/validation/validate.js:91:24)
affine_server | at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
affine_server | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
affine_server | at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
affine_server | at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
affine_server | at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)

Please suggest on how to fix this

**Comment by emengweb** [comment]
got same issus

**Comment by HYQ199506** [comment]
We need more configuration functions/webpage configuration functions to change the corresponding functions of OpenAI to self built or large models provided by other vendors, and to test the usability of workflow, image, chat and other functions after reconfiguration.

**Comment by HYQ199506** [comment]
> 我们需要更多的配置功能 / 网页配置功能，将 OpenAI 的相应功能改为自建或其他厂商提供的大型模型，并测试重新配置后的工作流、图片、聊天等功能的可用性。

If using Llama3 self built services, images, flowcharts, and other content cannot be used. How should I configure it.

**Comment by sFritsch09** [comment]
I also would like to mention why it makes sense to change OpenAI BaseURL for a lot of people:
You can use OpenRouter and still have access to OpenAI models: `https://openrouter.ai/api/v1`

There is just one thing to consider that with OpenRouter you cannot use **Dall-E** for image generation so this functionality needs to be turned of here: `packages/backend/server/src/plugins/copilot/providers/openai.ts` or add new provider 🙌

**Comment by v3ss0n** [comment]
Anyway to do that on Deskto Editor? need to modify and recompile i guess.

**Comment by samyogdhital** [comment]
+1 and looking for this feature.
Also consider adding gemini, groq and all as well team.

**Comment by joebnb** [comment]
add openai like API support i think is enough, most saas or self hosted llm are support that format api

**Comment by joebnb** [comment]
i‘m watching https://refly.ai/ this now

**Comment by arsaboo** [comment]
@joebnb Refly looks good...with Ollama and configurable API support. I hope Affine adds those as well soon.

**Comment by boom404** [comment]
> +1 and looking for this feature. Also consider adding gemini, groq and all as well team.

I created a small python script, who is between Affine and Gemini. All requets from Affine are send to my script and answered by Gemini.

https://github.com/boom404/affine-copilot-fix
