### ISSUE TITLE
​Help ME!~~~

### ISSUE THREAD

**Issue by xibidix** [toeverything/AFFiNE#8106]
### What happened?

I found an introduction to Affine online and really like its features! So I decided to deploy it locally, but I'm not a professional. I tried many operations, and due to network issues in China, pulling the images also had problems. However, I managed to resolve those.

I have tried deploying it on both Synology NAS and the company's server, but I haven't succeeded even once.

The failure is manifested in that when I open http://localhost:3010/ in my local network, there is no response. However, the Docker container shows that it is running normally. I have tried various methods through BTpanel, 1panel, Container Manager, and Portainer, but none of them worked.

I am close to giving up on deploying Affine locally as I have not been successful.

I referred to https://docs.affine.pro/docs/self-host-affine for deploying Docker.

Below is the YAML configuration for the deployment.

I hope to find a solution and successfully deploy it.

### Distribution version

Linux

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
running predeploy script.
yarn run v1.22.22
$ yarn prisma migrate deploy && node --import ./scripts/register.js ./dist/data/index.js run
$ /app/node_modules/.bin/prisma migrate deploy
Error: request to https://binaries.prisma.sh/all_commits/393aa359c9ad4a4bb28630fb5613f9c281cde053/debian-openssl-3.0.x/schema-engine.sha256 failed, reason: 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
node:internal/errors:984
  const err = new Error(message);
              ^
Error: Command failed: yarn predeploy
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at runPredeployScript (file:///app/scripts/self-host-predeploy.js:67:3)
    at file:///app/scripts/self-host-predeploy.js:75:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
�      
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 19,
  stdout: null,
  stderr: null
}
Node.js v20.16.0
running predeploy script.
yarn run v1.22.22
$ yarn prisma migrate deploy && node --import ./scripts/register.js ./dist/data/index.js run
$ /app/node_modules/.bin/prisma migrate deploy
```

### Anything else?

Below is the YAML configuration for the deployment.

```
services:
  affine:
    image: ghcr.io/toeverything/affine-graphql:stable
    container_name: affine_selfhosted
    command:
      ['sh', '-c', 'node ./scripts/self-host-predeploy && node ./dist/index.js']
    ports:
      - '3010:3010'
      - '5555:5555'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      # custom configurations
      - /volume2/docker/affine/config:/root/.affine/config
      # blob storage
      - /volume2/docker/affine/storage:/root/.affine/storage
    logging:
      driver: 'json-file'
      options:
        max-size: '1000m'
    restart: unless-stopped
    environment:
      # - NODE_OPTIONS="--import=./scripts/register.js"
      - NODE_OPTIONS="--es-module-specifier-resolution=node"
      - AFFINE_CONFIG_PATH=/root/.affine/config
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgres://affine:affine@postgres:5432/affine
      - NODE_ENV=production
      - AFFINE_ADMIN_EMAIL=123456@163.com
      - AFFINE_ADMIN_PASSWORD=a123456
  redis:
    image: redis:latest
    container_name: affine_redis
    restart: unless-stopped
    volumes:
      - /volume2/docker/affine/redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:latest
    container_name: affine_postgres
    restart: unless-stopped
    volumes:
      - /volume2/docker/affine/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U affine']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: affine
      POSTGRES_PASSWORD: affine
      POSTGRES_DB: affine
      PGDATA: /var/lib/postgresql/data/pgdata
```

This is the running log of affine_redis.

```
1:C 03 Sep 2024 06:50:02.713 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:C 03 Sep 2024 06:50:02.713 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 03 Sep 2024 06:50:02.713 * Redis version=7.4.0, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 03 Sep 2024 06:50:02.713 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 03 Sep 2024 06:50:02.714 * monotonic clock: POSIX clock_gettime
1:M 03 Sep 2024 06:50:02.715 * Running mode=standalone, port=6379.
1:M 03 Sep 2024 06:50:02.715 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 03 Sep 2024 06:50:02.715 * Server initialized
1:M 03 Sep 2024 06:50:02.716 * Loading RDB produced by version 7.4.0
1:M 03 Sep 2024 06:50:02.716 * RDB age 35 seconds
1:M 03 Sep 2024 06:50:02.716 * RDB memory usage when created 0.93 Mb
1:M 03 Sep 2024 06:50:02.716 * Done loading RDB, keys loaded: 1, keys expired: 0.
1:M 03 Sep 2024 06:50:02.716 * DB loaded from disk: 0.000 seconds
1:M 03 Sep 2024 06:50:02.716 * Ready to accept connections tcp
1:M 03 Sep 2024 07:07:19.847 * 100 changes in 300 seconds. Saving...
1:M 03 Sep 2024 07:07:19.847 * Background saving started by pid 624
624:C 03 Sep 2024 07:07:20.149 * DB saved on disk
624:C 03 Sep 2024 07:07:20.149 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
1:M 03 Sep 2024 07:07:20.250 * Background saving terminated with success
1:M 03 Sep 2024 07:25:10.568 * 100 changes in 300 seconds. Saving...
1:M 03 Sep 2024 07:25:10.568 * Background saving started by pid 1227
1227:C 03 Sep 2024 07:25:10.845 * DB saved on disk
1227:C 03 Sep 2024 07:25:10.846 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
1:M 03 Sep 2024 07:25:10.871 * Background saving terminated with success
1:M 03 Sep 2024 07:42:19.937 * 100 changes in 300 seconds. Saving...
1:M 03 Sep 2024 07:42:19.938 * Background saving started by pid 1831
1831:C 03 Sep 2024 07:42:20.232 * DB saved on disk
1831:C 03 Sep 2024 07:42:20.232 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
1:M 03 Sep 2024 07:42:20.241 * Background saving terminated with success
```

This is the running log of affine_postgres.

```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-03 06:50:04.944 UTC [1] LOG:  starting PostgreSQL 16.4 (Debian 16.4-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-09-03 06:50:04.952 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-09-03 06:50:04.952 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-09-03 06:50:05.047 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-09-03 06:50:05.148 UTC [29] LOG:  database system was shut down at 2024-09-03 06:49:28 UTC
2024-09-03 06:50:05.242 UTC [1] LOG:  database system is ready to accept connections
2024-09-03 06:55:05.219 UTC [27] LOG:  checkpoint starting: time
2024-09-03 06:55:05.766 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.142 s, total=0.548 s; sync files=2, longest=0.075 s, average=0.071 s; distance=0 kB, estimate=0 kB; lsn=0/19539E0, redo lsn=0/19539A8
```

**Comment by forehalo** [comment]
we can't help with network issue
