### ISSUE TITLE
Cannot get the Mail Service to correctly configure

### ISSUE THREAD

**Issue by tvtechdir** [toeverything/AFFiNE#8408]
### What happened?

I've put all my email credentials in the Compose.yaml file but continue to get 501 Syntax errors in the log. On the screen I get a GraphQL Error, Too Many Requests. Otherwise it looks like I should be able to send email, both invites and email validations.

<img width="1426" alt="Screenshot 2024-09-26 at 7 49 27 PM" src="https://github.com/user-attachments/assets/34e02c5e-ddbb-42e3-8c98-4cfcb65501b4">

My Compose.yaml file:

services:
  affine:
    image: ghcr.io/toeverything/affine-graphql:stable
    container_name: affine_selfhosted
    command:
      ['sh', '-c', 'node ./scripts/self-host-predeploy && node ./dist/index.js']
    ports:
      - '3010:3010'
      - '5555:5555'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      # custom configurations
      - ./.affine/self-host/config:/root/.affine/config
      # blob storage
      - ./.affine/self-host/storage:/root/.affine/storage
    logging:
      driver: 'json-file'
      options:
        max-size: '1000m'
    restart: unless-stopped
    environment:
      - NODE_OPTIONS="--import=./scripts/register.js"
      - AFFINE_CONFIG_PATH=/root/.affine/config
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgres://affine:***@postgres:5432/affine
      - NODE_ENV=production
      - AFFINE_ADMIN_EMAIL=affine username
      - AFFINE_ADMIN_PASSWORD=affine password
      - AFFINE_SERVER_HTTPS=true
      - AFFINE_SERVER_EXTERNAL_URL=https://my.doman.com
      - MAILER_HOST=smtp.ionos.com
      - MAILER_PORT=465
      - MAILER_SECURE=false
      - MAILER_USER=myemail@domain.com
      - MAILER_PASSWORD=password-with-these-dashes
      - MAILER_SENDER=my name <myemail@domain.com>
      # Telemetry allows us to collect data on how you use the affine. This data will helps us improve the app and provide better features.
      # Uncomment next line if you wish to quit telemetry.
      - TELEMETRY_ENABLE=false
  redis:
    image: redis
    container_name: affine_redis
    restart: unless-stopped
    volumes:
      - ./.affine/self-host/redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres
    container_name: affine_postgres
    restart: unless-stopped
    volumes:
      - ./.affine/self-host/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U affine']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: affine
      POSTGRES_PASSWORD: ***
      POSTGRES_DB: affine
      PGDATA: /var/lib/postgresql/data/pgdata

### Distribution version

Linux

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
affine_selfhosted  | [Nest] 117  - 09/27/2024, 2:39:45 AM    WARN [WorkspaceResolver] failed to send a26a2159-97a1-4a88-87d8-342f6ab61e39 invite email to ryan.andrews@fox.com, but successfully revoked permission: Error: Mail command failed: 501 Syntax error in parameters or arguments
affine_selfhosted  | [Nest] 117  - 09/27/2024, 2:39:45 AM   ERROR [WorkspaceResolver] failed to invite user
affine_selfhosted  | [Nest] 117  - 09/27/2024, 2:39:45 AM   ERROR [WorkspaceResolver] internal_server_error: An internal error occurred.
affine_selfhosted  | [Nest] 117  - 09/27/2024, 2:40:28 AM    WARN [WorkspaceResolver] failed to send a26a2159-97a1-4a88-87d8-342f6ab61e39 invite email to ryan.andrews@fox.com, but successfully revoked permission: Error: Mail command failed: 501 Syntax error in parameters or arguments
affine_selfhosted  | [Nest] 117  - 09/27/2024, 2:40:28 AM   ERROR [WorkspaceResolver] failed to invite user
affine_selfhosted  | [Nest] 117  - 09/27/2024, 2:40:28 AM   ERROR [WorkspaceResolver] internal_server_error: An internal error occurred.
affine_selfhosted  | [Nest] 117  - 09/27/2024, 2:40:28 AM VERBOSE [CacheInterceptor] cache blobs:a26a2159-97a1-4a88-87d8-342f6ab61e39 hit
affine_selfhosted  | [Nest] 117  - 09/27/2024, 2:41:29 AM VERBOSE [CacheInterceptor] cache blobs:a26a2159-97a1-4a88-87d8-342f6ab61e39 hit
affine_selfhosted  | [Nest] 117  - 09/27/2024, 2:42:30 AM VERBOSE [CacheInterceptor] cache blobs:a26a2159-97a1-4a88-87d8-342f6ab61e39 hit
affine_selfhosted  | [Nest] 117  - 09/27/2024, 2:43:31 AM VERBOSE [CacheInterceptor] cache blobs:a26a2159-97a1-4a88-87d8-342f6ab61e39 hit
affine_selfhosted  | [Nest] 117  - 09/27/2024, 2:44:32 AM VERBOSE [CacheInterceptor] cache blobs:a26a2159-97a1-4a88-87d8-342f6ab61e39 hit
affine_selfhosted  | [Nest] 117  - 09/27/2024, 2:45:33 AM VERBOSE [CacheInterceptor] cache blobs:a26a2159-97a1-4a88-87d8-342f6ab61e39 hit
affine_selfhosted  | [Nest] 117  - 09/27/2024, 2:46:34 AM VERBOSE [CacheInterceptor] cache blobs:a26a2159-97a1-4a88-87d8-342f6ab61e39 hit
affine_selfhosted  | [Nest] 117  - 09/27/2024, 2:47:03 AM VERBOSE [CacheInterceptor] cache blobs:a26a2159-97a1-4a88-87d8-342f6ab61e39 hit
affine_selfhosted  | [Nest] 117  - 09/27/2024, 2:47:17 AM   ERROR [GraphQL] Internal server error
affine_selfhosted  | Error: Mail command failed: 501 Syntax error in parameters or arguments
affine_selfhosted  |     at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:807:19)
affine_selfhosted  |     at SMTPConnection._actionMAIL (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1616:34)
affine_selfhosted  |     at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1085:18)
affine_selfhosted  |     at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:991:20)
affine_selfhosted  |     at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:772:14)
affine_selfhosted  |     at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
affine_selfhosted  |     at TLSSocket.emit (node:events:519:28)
affine_selfhosted  |     at addChunk (node:internal/streams/readable:559:12)
affine_selfhosted  |     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
affine_selfhosted  |     at Readable.push (node:internal/streams/readable:390:5)
```

**Comment by forehalo** [comment]
how about this
```diff
- MAILER_SENDER=my name myemail@domain.com
+ MAILER_SENDER=myemail@domain.com
```

**Comment by tvtechdir** [comment]
I was in a rush, the myemail@domain.com was written with <> on either side. Not sure if that makes a differnce.

I'm savvy enough to be dangerous with docker compose, but not knowledgable. Do I even need the MAILER_SENDER environment?

**Comment by tvtechdir** [comment]
> how about this
> 
> ```diff
> - MAILER_SENDER=my name myemail@domain.com
> + MAILER_SENDER=myemail@domain.com
> ```

Still getting 501 Syntax errors.

**Comment by forehalo** [comment]
yes, MAILER_USER is used to authenticate the mailer service, MAILER_SENDER is the mail shown in sender

**Comment by cyh-97** [comment]
我也遇到这个问题，应该是你的邮箱配置有误，检查你的邮箱能否正常登录，smtp是否错误

![Image](https://github.com/user-attachments/assets/4d8f4c13-7769-4d41-a540-c1b1c95ccbb0)

**Comment by cnmicha** [comment]
@forehalo 

> I was in a rush, the [myemail@domain.com](mailto:myemail@domain.com) was written with <> on either side. Not sure if that makes a differnce.

Make sure to have the sender email configured as a pure email address in the format `mbox@example.com`, and NOT including a sender name like `AFFiNE Server <mbox@example.com>`, even though the admin panel indicates that this is possible. Also do not include brackets `<` `>`. Entering a pure email address solved the issue for me.

See #10071
