### ISSUE TITLE
Copilot Plugins in affine.js: "You have reached the limit of actions" error after a few interactions, despite having token balance.

### ISSUE THREAD

**Issue by NuerSir** [toeverything/AFFiNE#8427]
## Issue Body:

I've successfully integrated Copilot Plugins into `affine.js` and configured it with OpenAI. The "Ask AI" feature works initially, but after approximately 10 interactions, I consistently receive the error message: "You have reached the limit of actions in this workspace, please upgrade your plan."

This occurs despite having a sufficient token balance in my OpenAI account. I've verified that making direct requests to OpenAI using `curl` works without any issues.

**Steps to reproduce:**

1. Integrate Copilot Plugins into `affine.js` and configure with OpenAI.
2. Use the "Ask AI" feature to interact with Copilot.
3. After approximately 10 interactions, the error message will appear.
![image](https://github.com/user-attachments/assets/f5a6fabe-bc08-417b-8e0a-27978cfa6cd2)

**Expected behavior:**

The "Ask AI" feature should continue to function as long as there is a sufficient token balance in the OpenAI account.

**Actual behavior:**

The "Ask AI" feature stops working after a limited number of interactions, regardless of token balance.

**Additional information:**

* Direct requests to OpenAI using `curl` work without any issues.
* This issue only occurs when using Copilot Plugins in `affine.js`.

**Possible causes:**

* Does AFFINE have a limit on the number of free times here? What do I need to do?

**Request:**

Please investigate this issue and provide a solution.

### Distribution version

Linux

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
{
    "errors": [
        {
            "message": "You have reached the limit of actions in this workspace, please upgrade your plan.",
            "locations": [
                {
                    "line": 3,
                    "column": 3
                }
            ],
            "path": [
                "createCopilotSession"
            ],
            "extensions": {
                "status": 402,
                "code": "Payment Required",
                "type": "QUOTA_EXCEEDED",
                "name": "COPILOT_QUOTA_EXCEEDED",
                "message": "You have reached the limit of actions in this workspace, please upgrade your plan.",
                "stacktrace": "copilot_quota_exceeded: You have reached the limit of actions in this workspace, please upgrade your plan.\n    at ChatSessionService.checkQuota (file:///app/dist/plugins/copilot/session.js:430:19)\n    at async CopilotResolver.createCopilotSession (file:///app/dist/plugins/copilot/resolver.js:414:13)"
            }
        }
    ],
    "data": null
}
```

**Comment by forehalo** [comment]
we are pushing the adaptation of ai for selfhost instances, but we haven't make it 100% ready. please be patient.

**Comment by NuerSir** [comment]
> we are pushing the adaptation of ai for selfhost instances, but we haven't make it 100% ready. please be patient.

@forehalo  After modifying Copilot, it works and the output results meet my expectations. However, AFFINE should have usage restrictions. I hope you can tell me where to modify to remove this restriction. Thank you very much.

**Comment by NuerSir** [comment]
> > we are pushing the adaptation of ai for selfhost instances, but we haven't make it 100% ready. please be patient.
> 
> @forehalo After modifying Copilot, it works and the output results meet my expectations. However, AFFINE should have usage restrictions. I hope you can tell me where to modify to remove this restriction. Thank you very much.

Please forgive my carelessness. I read the code and found the limitation in the `features` table. It can be used normally now. I hope AFFINE itself can have a more friendly and open way to access more LLM. I will look forward to it.

**Comment by EnGassa** [comment]
@NuerSir I'm trying to do something similar. Could you please share what you ended up doing to setup the Affine copilot with a custom LLM?

**Comment by richie80** [comment]
Hi, i am also having the same problem. (also using my own openAI key)
@NuerSir what did you modify?

OK / already found it:  https://github.com/toeverything/AFFiNE/issues/6641#issuecomment-2119875179

**Comment by danktankk** [comment]
I am also limited for AI even though I am using my own LLM and API key.  still blocked and I have also tried the postgres feature commands from #6641

Any ideas?  I just found this project and really like it so far.
