### ISSUE TITLE
​bug: `/app/static/selfhost/` directory does not exist

### ISSUE THREAD

**Issue by xymeng16** [toeverything/AFFiNE#8521]
### What happened?

Starting from canary docker image `canary-9a997e7`, the `/app/static/selfhost/` directory does not exist and trigger an error during predeploy.

I cannot find the corresponding commit for this canary image, but I have tested the canary image `canary-3d3a66c` and it works fine. This is the last workable image version. I hope this information is helpful.

### Distribution version

Linux

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
[Nest] 103  - 10/16/2024, 7:04:27 PM   ERROR [ExceptionHandler] ENOENT: no such file or directory, open '/app/static/selfhost/assets-manifest.json'
Error: ENOENT: no such file or directory, open '/app/static/selfhost/assets-manifest.json'
    at readFileSync (node:fs:448:20)
    at DocRendererController.readHtmlAssets (file:///app/dist/core/doc-renderer/controller.js:176:39)
    at new DocRendererController (file:///app/dist/core/doc-renderer/controller.js:48:31)
    at Injector.instantiateClass (/app/node_modules/@nestjs/core/injector/injector.js:365:19)
    at callback (/app/node_modules/@nestjs/core/injector/injector.js:65:45)
    at async Injector.resolveConstructorParams (/app/node_modules/@nestjs/core/injector/injector.js:144:24)
    at async Injector.loadInstance (/app/node_modules/@nestjs/core/injector/injector.js:70:13)
    at async Injector.loadController (/app/node_modules/@nestjs/core/injector/injector.js:88:9)
    at async /app/node_modules/@nestjs/core/injector/instance-loader.js:68:13
    at async Promise.all (index 0)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
node:internal/errors:984
  const err = new Error(message);
              ^
affine_selfhosted  |
Error: Command failed: yarn predeploy
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at execSync (node:child_process:963:15)
    at runPredeployScript (file:///app/scripts/self-host-predeploy.js:67:3)
    at file:///app/scripts/self-host-predeploy.js:75:1
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 20,
  stdout: null,
  stderr: null
}
affine_selfhosted  |
Node.js v20.18.0
affine_selfhosted exited with code 1
```

**Comment by LIHAQ** [comment]
me too

**Comment by xymeng16** [comment]
> me too

Seems https://github.com/toeverything/AFFiNE/pull/8530 fixes this issue.

I will test when the canary image including this commit releases.
