### ISSUE TITLE
​cannot copy in the document

### ISSUE THREAD

**Issue by BadboyXiaobai** [toeverything/AFFiNE#8585]
### What happened?

I have deployed the AFFiNE service on my NAS server, which runs the latest version of Feiniu O,AFFiNE version is 0.16.0-nightly-eb0466e. I used the official script to deploy it to Docker with one click. During use, I found that I cannot copy any content from the document to the clipboard, but I can paste the clipboard content into the document. When I pressed F12 to check the browser console information, I found an error when copying, and the error message is as follows：
`TypeError: Cannot read properties of undefined (reading 'write')
    at h.writeToClipboard (index.ts:357:31)
    at async h.copySlice (index.ts:168:5)`

I suspect there might be an issue with my installation script or the AFFiNE version, so I cloned the latest version of the software from GitHub and installed it in Docker using compose.yaml. The version number is 0.17.5, but the problem persists. Therefore, I believe it might be a software issue rather than a system or configuration problem. I'm going to provide feedback on GitHub, hoping it can contribute to the project.

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome, Microsoft Edge

### Are you self-hosting?

- [X] Yes

**Comment by forehalo** [comment]
`navigator.clipboard` api is used in copy module and it requires secure context(https) in non-localhost environment. Im hoping @fourdim is on this, replacing `navigator.clipboard` with `ClipboardEvent` if it's blocked

**Comment by fourdim** [comment]
Closed by https://github.com/toeverything/blocksuite/pull/8587
Noted, you will experience performance downgrade if secure context is disabled.

Include but not limit to:
- Cannot copy image
- Copied text are malformed
- Copied text does not have any styles
- Pasted text are malformed
- Pasted text does not have any styles
- The editor works abnormally after paste

You can still enable the secure context by following the guideline below:
https://docs.affine.pro/docs/self-host-affine#why-my-selfhosted-version-does-not-support-copy--paste

**Comment by patschwork** [comment]
Hi, 
I'm currently testing AFFiNE (installed via Docker some days ago) :-) also stumpled upon this problem, that copy&paste didn't work.

Tested on:
- Vivaldi Browser (Chrome based browser)
- Firefox
- AFFiNE App (on MacOS)

Setup is also self-hosted (access to non local server). 
I think, my installation is beyond this fix https://github.com/toeverything/blocksuite/pull/8587 (?)


>You can still enable the secure context by following the guideline below:
https://docs.affine.pro/docs/self-host-affine#why-my-selfhosted-version-does-not-support-copy--paste

Setting the flag in the browser works "enables" copy&paste and then it works (but this a very local workaround). 

Besides I'm also using [DocMate](https://github.com/Neumand/docmate), which also has a Markdown'ish editor: There <u>**no problems on copy&paste**</u> (also self-hosted, no cert, very equal config as AFFiNE). 
Maybe this is a hint to have a look, how they solved this.... ;-)


PS: AFFiNE looks great so far -> Thank you for all the work!
