### ISSUE TITLE
​Using OpenAI ChatGPT

### ISSUE THREAD

**Issue by dwulfing** [toeverything/AFFiNE#8674]
### What happened?

I have add the env Value "COPILOT_OPENAI_API_KEY=sk-svcacct-Q..." to activate Affine AI on my Self Hosted Docker instance.

I gat this errors:
GraphQLError: Unknown type "QueryChatHistoriesInput".
    at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)
    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
    at visit (/app/node_modules/graphql/language/visitor.js:197:21)
    at validate (/app/node_modules/graphql/validation/validate.js:91:24)
    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)

and some more...

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
[Nest] 117  - 11/03/2024, 9:24:43 PM   ERROR [GraphQL] Internal server error
GraphQLError: Unknown type "CreateChatSessionInput". Did you mean "CreateUserInput"?
    at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)
    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
    at visit (/app/node_modules/graphql/language/visitor.js:197:21)
    at validate (/app/node_modules/graphql/validation/validate.js:91:24)
    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
[Nest] 117  - 11/03/2024, 9:24:43 PM   ERROR [GraphQL] Internal server error
GraphQLError: Cannot query field "createCopilotSession" on type "Mutation".
    at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)
    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
    at visit (/app/node_modules/graphql/language/visitor.js:197:21)
    at validate (/app/node_modules/graphql/validation/validate.js:91:24)
    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
```

**Comment by beanaroo** [comment]
I am also experiencing these errors. Perhaps due to version inconsistency? (I'm using the latest `compose.yaml`)

![image](https://github.com/user-attachments/assets/e0c742e7-3c54-4338-b6e5-42955762177c)

```
[Nest] 125  - 11/10/2024, 2:25:21 AM   ERROR [GraphQL] Internal server error
GraphQLError: Unknown type "QueryChatHistoriesInput".
    at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)
    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
    at visit (/app/node_modules/graphql/language/visitor.js:197:21)
    at validate (/app/node_modules/graphql/validation/validate.js:91:24)
    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)

[Nest] 125  - 11/10/2024, 2:25:21 AM   ERROR [GraphQL] Internal server error
GraphQLError: Cannot query field "copilot" on type "UserType".
    at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)
    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
    at visit (/app/node_modules/graphql/language/visitor.js:197:21)
    at validate (/app/node_modules/graphql/validation/validate.js:91:24)
    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)

[Nest] 125  - 11/10/2024, 2:25:21 AM   ERROR [GraphQL] Internal server error
GraphQLError: Unknown type "QueryChatHistoriesInput".
    at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)
    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
    at visit (/app/node_modules/graphql/language/visitor.js:197:21)
    at validate (/app/node_modules/graphql/validation/validate.js:91:24)
    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
```

**Comment by totalcaos** [comment]
I am facing the same issues as here.  I have updated to the latest affine docker image (Affine version 0.18.2, Editor version 
0.17.33), and get these error messages:

affine_server         | [Nest] 1  - 12/12/2024, 4:45:09 AM   DEBUG [PgWorkspaceDocStorageAdapter] History created for v8wAztX1IaO8OlGscKt9K in workspace 727a3c72-6486-4547-989e-51dbb20b2fc1.
affine_server         | [Nest] 1  - 12/12/2024, 4:45:14 AM   ERROR [GraphQL] Internal server error
affine_server         | GraphQLError: Unknown type "CreateChatSessionInput". Did you mean "CreateUserInput"?
affine_server         |     at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)
affine_server         |     at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
affine_server         |     at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
affine_server         |     at visit (/app/node_modules/graphql/language/visitor.js:197:21)
affine_server         |     at validate (/app/node_modules/graphql/validation/validate.js:91:24)
affine_server         |     at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
affine_server         |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
affine_server         |     at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
affine_server         |     at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
affine_server         |     at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
affine_server         | [Nest] 1  - 12/12/2024, 4:45:14 AM   ERROR [GraphQL] Internal server error
affine_server         | GraphQLError: Cannot query field "createCopilotSession" on type "Mutation".
affine_server         |     at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)
affine_server         |     at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
affine_server         |     at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
affine_server         |     at visit (/app/node_modules/graphql/language/visitor.js:197:21)
affine_server         |     at validate (/app/node_modules/graphql/validation/validate.js:91:24)
affine_server         |     at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
affine_server         |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
affine_server         |     at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
affine_server         |     at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
affine_server         |     at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)

**Comment by ArnoChenFx** [comment]
Same issues， Affine version 0.18.2
```
[Nest] 1  - 12/12/2024, 5:36:10 AM   ERROR [GraphQL] Internal server error

GraphQLError: Unknown type "QueryChatHistoriesInput".

    at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)

    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)

    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)

    at visit (/app/node_modules/graphql/language/visitor.js:197:21)

    at validate (/app/node_modules/graphql/validation/validate.js:91:24)

    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)

    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)

    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)

[Nest] 1  - 12/12/2024, 5:36:10 AM   ERROR [GraphQL] Internal server error

GraphQLError: Cannot query field "copilot" on type "UserType".

    at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)

    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)

    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)

    at visit (/app/node_modules/graphql/language/visitor.js:197:21)

    at validate (/app/node_modules/graphql/validation/validate.js:91:24)

    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)

    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)

    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)

[Nest] 1  - 12/12/2024, 5:36:10 AM   ERROR [GraphQL] Internal server error

GraphQLError: Unknown type "QueryChatHistoriesInput".

    at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)

    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)

    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)

    at visit (/app/node_modules/graphql/language/visitor.js:197:21)

    at validate (/app/node_modules/graphql/validation/validate.js:91:24)

    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)

    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)

    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)

[Nest] 1  - 12/12/2024, 5:36:10 AM   ERROR [GraphQL] Internal server error

GraphQLError: Cannot query field "copilot" on type "UserType".

    at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)

    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)

    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)

    at visit (/app/node_modules/graphql/language/visitor.js:197:21)

    at validate (/app/node_modules/graphql/validation/validate.js:91:24)

    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)

    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)

    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)

[Nest] 1  - 12/12/2024, 5:36:17 AM   ERROR [GraphQL] Internal server error

GraphQLError: Unknown type "CreateChatSessionInput". Did you mean "CreateUserInput"?

    at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)

    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)

    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)

    at visit (/app/node_modules/graphql/language/visitor.js:197:21)

    at validate (/app/node_modules/graphql/validation/validate.js:91:24)

    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)

    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)

    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)

[Nest] 1  - 12/12/2024, 5:36:17 AM   ERROR [GraphQL] Internal server error

GraphQLError: Cannot query field "createCopilotSession" on type "Mutation".

    at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)

    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)

    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)

    at visit (/app/node_modules/graphql/language/visitor.js:197:21)

    at validate (/app/node_modules/graphql/validation/validate.js:91:24)

    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)

    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)

    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
```

**Comment by mxsergeev** [comment]
Also getting the same errors on 0.18.2

```
affine_server         | [Nest] 1  - 12/25/2024, 10:18:07 PM   ERROR [GraphQL] Internal server error
affine_server         | GraphQLError: Unknown type "CreateChatSessionInput". Did you mean "CreateUserInput"?
affine_server         |     at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)
affine_server         |     at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
affine_server         |     at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
affine_server         |     at visit (/app/node_modules/graphql/language/visitor.js:197:21)
affine_server         |     at validate (/app/node_modules/graphql/validation/validate.js:91:24)
affine_server         |     at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
affine_server         |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
affine_server         |     at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
affine_server         |     at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
affine_server         |     at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
affine_server         | [Nest] 1  - 12/25/2024, 10:18:07 PM   ERROR [GraphQL] Internal server error
affine_server         | GraphQLError: Cannot query field "createCopilotSession" on type "Mutation".
affine_server         |     at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)
affine_server         |     at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
affine_server         |     at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
affine_server         |     at visit (/app/node_modules/graphql/language/visitor.js:197:21)
affine_server         |     at validate (/app/node_modules/graphql/validation/validate.js:91:24)
affine_server         |     at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
affine_server         |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
affine_server         |     at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
affine_server         |     at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
affine_server         |     at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
```

**Comment by richie80** [comment]
Apparently you have to use a Legacy User API key of OpenAI and not the project key.

**Comment by totalcaos** [comment]
I am using the legacy User API key - still get that error

**Comment by LeoMartinDev** [comment]
Is this going to be addressed ?

**Comment by ArnoChenFx** [comment]
> Is this going to be addressed ?

The latest version has solved my issue.

**Comment by endquote** [comment]
I'm seeing the issue on the current `ghcr.io/toeverything/affine-graphql:stable` image. I'm using `COPILOT_OPENAI_API_KEY` and have tried both the "user" and "service account" style API keys. The about screen shows 0.19.6.

**Comment by nagelxz** [comment]
@endquote I'm pretty sure that's something that will be in 0.20 (or whatever their next release will be). Release 0.19.6 was published 2 weeks ago and the above linked PR is only 4 days old. You can try switching to one of the canary releases.

Just trying to be helpful, ran into the same issue and came looking for how to turn it on manually as well :)

**Comment by Pedromigacz** [comment]
I'm facing something similar on the latest cannary (`0.19.0-nightly-6370f45`):

![Image](https://github.com/user-attachments/assets/3d56dff7-67e4-429e-80cf-b055225c4a90)

Here are my logs for both `chat ai` requests and `space autocomplete` requests:
```
 [Nest] 127  - 01/27/2025, 4:18:13 AM   ERROR ;5;3m[GraphQL] <req-fdd0e678-4e71-4e1b-9790-e4265e035924> internal_server_error
 GraphQLError: Unknown type "CreateChatSessionInput". Did you mean "CreateUserInput"?
     at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)
     at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
     at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
     at visit (/app/node_modules/graphql/language/visitor.js:197:21)
     at validate (/app/node_modules/graphql/validation/validate.js:91:24)
     at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
     at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
     at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
     at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
 [Nest] 127  - 01/27/2025, 4:18:13 AM   ERROR ;5;3m[GraphQL] <req-fdd0e678-4e71-4e1b-9790-e4265e035924> internal_server_error
GraphQLError: Cannot query field "createCopilotSession" on type "Mutation".
     at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)
     at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
     at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
     at visit (/app/node_modules/graphql/language/visitor.js:197:21)
     at validate (/app/node_modules/graphql/validation/validate.js:91:24)
     at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
     at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
     at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
     at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
```
Do  you guys think it's related or should I open a new issue?
The result is still the same, affinity ai is unusable on self-hosted 🥲

**Comment by ArnoChenFx** [comment]
Here are the steps I took to successfully enable the AI feature in self-hosted Affine (v0.19.6):

1. Open the `affine.js` (in the path specified by `CONFIG_LOCATION` in the `.env` file)
2. Add the following content at the end of the file
```javascript
AFFiNE.use('copilot', {
  openai: {
    baseURL: 'https://api.openai.com/v1',
    apiKey: 'your-api-key',
  },
})
```
3. Restart the Affine docker compose

I didn't add the `COPILOT_OPENAI_API_KEY` environment variable.

![Image](https://github.com/user-attachments/assets/86bac17e-83b9-423a-b14e-77fab3431446)

**Comment by Pedromigacz** [comment]
Damn, I think this was just disabled by choice then. If you add it like:
```ts
AFFiNE.use('copilot', {
  openai: {
    apiKey: process.env.COPILOT_OPENAI_API_KEY,
  },
})
```
It works like the documentation suggests...

**Comment by eikaramba** [comment]
does anynone know how this looks like with the new config schema from https://github.com/toeverything/AFFiNE/releases/tag/v0.21.0 ?
