### ISSUE TITLE
multiple message ERROR [GraphQL] Internal server error​

### ISSUE THREAD

**Issue by Tealk** [toeverything/AFFiNE#8988]
### What happened?

I installed the software on my computer for test purposes and accessed it via localhost and got the error message below for all accesses to notes

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Firefox

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
affine_selfhosted  | [Nest] 165  - 12/02/2024, 5:00:42 PM   ERROR [GraphQL] Internal server error
affine_selfhosted  | GraphQLError: Unknown type "QueryChatHistoriesInput".
affine_selfhosted  |     at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
affine_selfhosted  |     at visit (/app/node_modules/graphql/language/visitor.js:197:21)
affine_selfhosted  |     at validate (/app/node_modules/graphql/validation/validate.js:91:24)
affine_selfhosted  |     at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
affine_selfhosted  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
affine_selfhosted  |     at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
affine_selfhosted  |     at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
affine_selfhosted  |     at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
affine_selfhosted  | [Nest] 165  - 12/02/2024, 5:00:42 PM   ERROR [GraphQL] Internal server error
affine_selfhosted  | GraphQLError: Cannot query field "copilot" on type "UserType".
affine_selfhosted  |     at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
affine_selfhosted  |     at visit (/app/node_modules/graphql/language/visitor.js:197:21)
affine_selfhosted  |     at validate (/app/node_modules/graphql/validation/validate.js:91:24)
affine_selfhosted  |     at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
affine_selfhosted  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
affine_selfhosted  |     at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
affine_selfhosted  |     at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
affine_selfhosted  |     at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
affine_selfhosted  | [Nest] 165  - 12/02/2024, 5:00:42 PM   ERROR [GraphQL] Internal server error
affine_selfhosted  | GraphQLError: Unknown type "QueryChatHistoriesInput".
affine_selfhosted  |     at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
affine_selfhosted  |     at visit (/app/node_modules/graphql/language/visitor.js:197:21)
affine_selfhosted  |     at validate (/app/node_modules/graphql/validation/validate.js:91:24)
affine_selfhosted  |     at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
affine_selfhosted  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
affine_selfhosted  |     at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
affine_selfhosted  |     at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
affine_selfhosted  |     at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
affine_selfhosted  | [Nest] 165  - 12/02/2024, 5:00:42 PM   ERROR [GraphQL] Internal server error
affine_selfhosted  | GraphQLError: Cannot query field "copilot" on type "UserType".
affine_selfhosted  |     at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
affine_selfhosted  |     at visit (/app/node_modules/graphql/language/visitor.js:197:21)
affine_selfhosted  |     at validate (/app/node_modules/graphql/validation/validate.js:91:24)
affine_selfhosted  |     at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
affine_selfhosted  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
affine_selfhosted  |     at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
affine_selfhosted  |     at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
affine_selfhosted  |     at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
```

**Comment by Tealk** [comment]
I don't quite understand, isn't an error message something that should be fixed?

**Comment by JimVincentW** [comment]
I get the same message, and my cloud workspace won't really load. Will look further into it but wanted to bump this.
