### ISSUE TITLE
cannot accept workspace invite

### ISSUE THREAD

**Issue by Arn-og** [toeverything/AFFiNE#9063]
### What happened?

I have invited 3 people to a workspace (pro version) only 1 of which has been able to join, the others remained "pending" after accepting the invite

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

**Comment by CatsJuice** [comment]
Could you please confirm if those users who were not successfully added are able to click **Accept** in the email and open the webpage to see the **Successfully joined** message?

**Comment by intbjw** [comment]
me too 

<img width="1160" alt="Image" src="https://github.com/user-attachments/assets/1cae6a82-2527-4766-a9f5-896b4f3b331a" />
this is log 


```
[Nest] 1  - 02/27/2025, 6:43:13 AM VERBOSE [Locker] <allinone:graphql:708b24fa-ddab-4ccc-8d6a-bbb84c6ea908> Client d9f99e5d-b404-4e3a-af2f-b7d6808ba2a6 is trying to lock resource invite:75640345-1db5-4ee0-9702-4099193fff29
[Nest] 1  - 02/27/2025, 6:43:14 AM   ERROR [GraphQL] <allinone:http:6114ad82-90c9-4939-a371-b808f9d0275a> internal_server_error
internal_server_error: An internal error occurred.
    at mapAnyError (file:///app/dist/base/nestjs/exception.js:46:19)
    at GlobalExceptionFilter.catch (file:///app/dist/base/nestjs/exception.js:57:23)
    at ExternalExceptionsHandler.invokeCustomFilters (/app/node_modules/@nestjs/core/exceptions/external-exceptions-handler.js:31:32)
    at ExternalExceptionsHandler.next (/app/node_modules/@nestjs/core/exceptions/external-exceptions-handler.js:14:29)
    at /app/node_modules/@nestjs/core/helpers/external-proxy.js:14:42
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Caused by:

Error: Message failed: 550 The recipient may contain a non-existent account, please check the recipient address.
    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:809:19)
    at SMTPConnection._actionSMTPStream (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1730:34)
    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1198:22)
    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)
    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)
    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
    at TLSSocket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)

```

**Comment by JimmFly** [comment]
We fixed the related issue in the 0.21 update. Is this problem still present in the latest version?

**Comment by intbjw** [comment]
no problem
