### ISSUE TITLE
​Share link not working after upgrading from 0.17.4 to 0.18.2

### ISSUE THREAD

**Issue by gaoshang212** [toeverything/AFFiNE#9087]
### What happened?

I upgraded from version 0.17.4 to 0.18.2, and now the share feature is no longer working. However, the data from the previous version (0.17.4) is still accessible and functioning correctly. It seems like the issue only appears after the data of upgrade .

![image](https://github.com/user-attachments/assets/246369e8-a35f-44e2-8b4e-a44ee6c4f48c)

this old data, can working.

![image](https://github.com/user-attachments/assets/6979de19-a4b1-4a97-a765-864bf4dde080)

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
affine_selfhosted  | [Nest] 117  - 12/10/2024, 6:26:31 AM VERBOSE [CacheInterceptor] cache blobs:dc5bc297-591f-4205-978b-379640ac29b9 miss
affine_selfhosted  | [Nest] 117  - 12/10/2024, 6:27:27 AM VERBOSE [CacheInterceptor] cache blobs:dc5bc297-591f-4205-978b-379640ac29b9 hit
affine_selfhosted  | [Nest] 117  - 12/10/2024, 6:27:28 AM   ERROR [GraphQL] Internal server error
affine_selfhosted  | GraphQLError: Unknown type "QueryChatHistoriesInput".
affine_selfhosted  |     at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
affine_selfhosted  |     at visit (/app/node_modules/graphql/language/visitor.js:197:21)
affine_selfhosted  |     at validate (/app/node_modules/graphql/validation/validate.js:91:24)
affine_selfhosted  |     at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
affine_selfhosted  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
affine_selfhosted  |     at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
affine_selfhosted  |     at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
affine_selfhosted  |     at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
affine_selfhosted  | [Nest] 117  - 12/10/2024, 6:27:28 AM   ERROR [GraphQL] Internal server error
affine_selfhosted  | GraphQLError: Cannot query field "copilot" on type "UserType".
affine_selfhosted  |     at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
affine_selfhosted  |     at visit (/app/node_modules/graphql/language/visitor.js:197:21)
affine_selfhosted  |     at validate (/app/node_modules/graphql/validation/validate.js:91:24)
affine_selfhosted  |     at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
affine_selfhosted  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
affine_selfhosted  |     at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
affine_selfhosted  |     at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
affine_selfhosted  |     at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
affine_selfhosted  | [Nest] 117  - 12/10/2024, 6:27:28 AM   ERROR [GraphQL] Internal server error
affine_selfhosted  | GraphQLError: Unknown type "QueryChatHistoriesInput".
affine_selfhosted  |     at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
affine_selfhosted  |     at visit (/app/node_modules/graphql/language/visitor.js:197:21)
affine_selfhosted  |     at validate (/app/node_modules/graphql/validation/validate.js:91:24)
affine_selfhosted  |     at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
affine_selfhosted  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
affine_selfhosted  |     at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
affine_selfhosted  |     at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
affine_selfhosted  |     at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
affine_selfhosted  | [Nest] 117  - 12/10/2024, 6:27:28 AM   ERROR [GraphQL] Internal server error
affine_selfhosted  | GraphQLError: Cannot query field "copilot" on type "UserType".
affine_selfhosted  |     at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
affine_selfhosted  |     at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
affine_selfhosted  |     at visit (/app/node_modules/graphql/language/visitor.js:197:21)
affine_selfhosted  |     at validate (/app/node_modules/graphql/validation/validate.js:91:24)
affine_selfhosted  |     at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
affine_selfhosted  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
affine_selfhosted  |     at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
affine_selfhosted  |     at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
affine_selfhosted  |     at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
affine_selfhosted  | [Nest] 117  - 12/10/2024, 6:28:27 AM VERBOSE [CacheInterceptor] cache blobs:dc5bc297-591f-4205-978b-379640ac29b9 hit
```

**Comment by forehalo** [comment]
any error in console when white screen?

**Comment by gaoshang212** [comment]
> any error in console when white screen?

no,  the log is when white screen.   the last only `cache blobs:dc5bc297-591f-4205-978b-379640ac29b9 hit.`

**Comment by gaoshang212** [comment]
> any error in console when white screen?

I just tried it, and it's working again. 😅
