### ISSUE TITLE
There are some errors log in console when I oepn a sample workspace

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/AFFiNE#912]

**Comment by tzhangchi** [comment]
https://www.loom.com/share/d3089b74f0414fc6b58530e2b95d6023


![Image](https://user-images.githubusercontent.com/5910926/217704855-e1d5312f-5bef-4e52-87af-4139d299ef64.png)

**Comment by tzhangchi** [comment]
```js
workbox-b777c91b.js:1 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://stage.affine.pro/_next/static/chunks/234-f65c101c8f898b2a.js.map","status":404}]
    at Y.j (https://stage.affine.pro/workbox-b777c91b.js:1:16890)
    at async Y.D (https://stage.affine.pro/workbox-b777c91b.js:1:16442)
    at async Y.R (https://stage.affine.pro/workbox-b777c91b.js:1:7597)
j @ workbox-b777c91b.js:1
setTimeout (async)
(anonymous) @ workbox-b777c91b.js:1
cachePut @ workbox-b777c91b.js:1
j @ workbox-b777c91b.js:1
await in j (async)
D @ workbox-b777c91b.js:1
await in D (async)
R @ workbox-b777c91b.js:1
await in R (async)
handleAll @ workbox-b777c91b.js:1
(anonymous) @ workbox-b777c91b.js:1
await in (anonymous) (async)
$ @ workbox-b777c91b.js:1
install @ workbox-b777c91b.js:1
_app-aa21ea40b654d8f2.js:288          HEAD https://stage.affine.pro/api/workspace/140ee5ed-17d1-47e1-86e8-47fc690ccf5c/blob/ECvPm5_4ksjh7WsV8bA00n8MW_WwwFrLyotv4mTwMHk= net::ERR_ABORTED 401
(anonymous) @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:288
_fetch @ _app-aa21ea40b654d8f2.js:288
await in _fetch (async)
r @ _app-aa21ea40b654d8f2.js:288
await in r (async)
_retry @ _app-aa21ea40b654d8f2.js:288
create @ _app-aa21ea40b654d8f2.js:288
t.<computed> @ _app-aa21ea40b654d8f2.js:288
_runTasks @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:288
Promise.then (async)
yn @ _app-aa21ea40b654d8f2.js:288
vn @ _app-aa21ea40b654d8f2.js:288
init @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:288
br @ _app-aa21ea40b654d8f2.js:288
D @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:288
loadWorkspaces @ _app-aa21ea40b654d8f2.js:288
init @ _app-aa21ea40b654d8f2.js:288
await in init (async)
(anonymous) @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:1
s @ main-a75f448466115afc.js:1
(anonymous) @ main-a75f448466115afc.js:1
forEach.e.<computed> @ main-a75f448466115afc.js:1
r @ _app-aa21ea40b654d8f2.js:288
a @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:1
(anonymous) @ _app-aa21ea40b654d8f2.js:1
ri @ react-dom.production.min.js:244
Ss @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
2_app-aa21ea40b654d8f2.js:288 close workspace websocket which not exist.
closeWorkspace @ _app-aa21ea40b654d8f2.js:288
loadWorkspace @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:1
s @ main-a75f448466115afc.js:1
(anonymous) @ main-a75f448466115afc.js:1
forEach.e.<computed> @ main-a75f448466115afc.js:1
r @ _app-aa21ea40b654d8f2.js:288
a @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:1
(anonymous) @ 918-42dce960899cc263.js:1
ri @ react-dom.production.min.js:244
Ss @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
all:1 Uncaught (in promise) undefined
setTimeout (async)
(anonymous) @ _app-aa21ea40b654d8f2.js:288
n @ _app-aa21ea40b654d8f2.js:1
(anonymous) @ _app-aa21ea40b654d8f2.js:1
emit @ _app-aa21ea40b654d8f2.js:1
Xe @ _app-aa21ea40b654d8f2.js:1
Qe @ _app-aa21ea40b654d8f2.js:1
ae @ _app-aa21ea40b654d8f2.js:1
ce @ _app-aa21ea40b654d8f2.js:1
t.applyUpdate @ _app-aa21ea40b654d8f2.js:1
(anonymous) @ _app-aa21ea40b654d8f2.js:288
N @ _app-aa21ea40b654d8f2.js:288
_applyCloudUpdates @ _app-aa21ea40b654d8f2.js:288
await in _applyCloudUpdates (async)
warpWorkspace @ _app-aa21ea40b654d8f2.js:288
loadWorkspace @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:1
s @ main-a75f448466115afc.js:1
(anonymous) @ main-a75f448466115afc.js:1
forEach.e.<computed> @ main-a75f448466115afc.js:1
r @ _app-aa21ea40b654d8f2.js:288
a @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:1
(anonymous) @ 918-42dce960899cc263.js:1
ri @ react-dom.production.min.js:244
Ss @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
3_app-aa21ea40b654d8f2.js:288 close workspace websocket which not exist.
closeWorkspace @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:288
loadWorkspace @ _app-aa21ea40b654d8f2.js:288
await in loadWorkspace (async)
(anonymous) @ _app-aa21ea40b654d8f2.js:1
s @ main-a75f448466115afc.js:1
(anonymous) @ main-a75f448466115afc.js:1
forEach.e.<computed> @ main-a75f448466115afc.js:1
r @ _app-aa21ea40b654d8f2.js:288
a @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:1
(anonymous) @ 918-42dce960899cc263.js:1
ri @ react-dom.production.min.js:244
Ss @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
_app-aa21ea40b654d8f2.js:288          GET https://stage.affine.pro/api/workspace/55aa5e66_676a_46cb_9d7f_44683500a6fb/blob/QVmsF1qXXdkaHxV48-JOGrau38tJwIhe77QCBwCzVpM= 404
(anonymous) @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ _app-aa21ea40b654d8f2.js:288
_fetch @ _app-aa21ea40b654d8f2.js:288
await in _fetch (async)
r @ _app-aa21ea40b654d8f2.js:288
await in r (async)
_retry @ _app-aa21ea40b654d8f2.js:288
create @ _app-aa21ea40b654d8f2.js:288
t.<computed> @ _app-aa21ea40b654d8f2.js:288
get @ _app-aa21ea40b654d8f2.js:288
get @ _app-aa21ea40b654d8f2.js:288
await in get (async)
get @ _app-aa21ea40b654d8f2.js:288
(anonymous) @ 292-1e8355aae46d6c0b.js:1
Promise.then (async)
(anonymous) @ 292-1e8355aae46d6c0b.js:1
ri @ react-dom.production.min.js:244
Ss @ react-dom.production.min.js:286
is @ react-dom.production.min.js:273
jl @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:283
ws @ react-dom.production.min.js:281
ls @ react-dom.production.min.js:270
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
_app-aa21ea40b654d8f2.js:288 Error while getting blob HTTPError: Request failed with status code 404
    at r (_app-aa21ea40b654d8f2.js:288:68606)
    at async un._retry (_app-aa21ea40b654d8f2.js:288:72772)
    at async i.<computed> [as blob] (_app-aa21ea40b654d8f2.js:288:69244)
    at async yn.get (_app-aa21ea40b654d8f2.js:288:76789)
    at async vn.get (_app-aa21ea40b654d8f2.js:288:77728)
    at async _n.get (_app-aa21ea40b654d8f2.js:288:78792)
```
