### ISSUE TITLE
Can not enable copilot plugin, only produces errors

### ISSUE THREAD

**Issue by wtfbbqhax** [toeverything/AFFiNE#9417]
### What happened?

# Problem Overview:

I followed the guild https://docs.affine.pro/docs/self-host-affine, and noted that the AI features are not working. After some digging and searching I found that there are undocumented requirements that I'm finding difficult to resolve. I've tried to solve this myself in piecemeal, but I suspect I'm missing some more fundamental requirements.

# Actual Results:

Whenver I invoke the AI Chat, I see the following errors in the logs:

```
[Nest] 1  - 12/29/2024, 11:45:48 AM   ERROR [GraphQL] Internal server error
GraphQLError: Unknown type "CreateChatSessionInput". Did you mean "CreateUserInput"?
    at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)
    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
    at visit (/app/node_modules/graphql/language/visitor.js:197:21)
    at validate (/app/node_modules/graphql/validation/validate.js:91:24)
    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
[Nest] 1  - 12/29/2024, 11:45:48 AM   ERROR [GraphQL] Internal server error
GraphQLError: Cannot query field "createCopilotSession" on type "Mutation".
    at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)
    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
    at visit (/app/node_modules/graphql/language/visitor.js:197:21)
    at validate (/app/node_modules/graphql/validation/validate.js:91:24)
    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
 ```
 
I believe at the root of the problem, I'm not even enabling the copilot plugin correctly, I see no indications in the affine_server startup that indicates copilot or openai is being loaded/initialized. 
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/4bbace28-5dfc-45ba-bc15-ed8025520461" />

I've modified my local `~/.affine/self-host/config/affine.js` like so (key scrubbed)
<img width="660" alt="Screenshot 2024-12-29 at 6 56 54 PM" src="https://github.com/user-attachments/assets/83515ffc-1435-4f72-8348-bdd4c5d5880b" />

And "restarted" the stack of software with `docker compose down` and `docker compose up -d` to restart.

I've also tried providing the API key using the `.env` file, restarting the stack of software same as above, but still no changes. 
<img width="587" alt="Screenshot 2024-12-29 at 6 58 59 PM" src="https://github.com/user-attachments/assets/68b3228b-b69d-4301-9e2f-e6100e187541" />

The result is always the same UI error, at best. However, many of the AI features produce no visible user errors or warnings. 

<img width="416" alt="Screenshot 2024-12-29 at 6 59 46 PM" src="https://github.com/user-attachments/assets/49d9f30e-8be8-4c86-84fd-4336ea16ac2a" />

# Expected Results

Hopefully a functional set of AI chat and other features..

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [ ] Yes

**Comment by Lanvaldear** [comment]
I also have this problem. Also as someone suggested i tried using legacy user API key and project API key.

**Comment by emengweb** [comment]
find out the datebase model has change to gpt-4o-2024-08-06 and gpt-4o-mini-2024-07-18, that cause custem api can not located the current AI model.

hope can add some way custem AI model name.

**Comment by GarryLai** [comment]
+1

**Comment by DoDoMan-TTT** [comment]
the same problem here

**Comment by wtfbbqhax** [comment]
> I also have this problem. Also as someone suggested i tried using legacy user API key and project API key.

Hopefully not, As I have no existing legacy keys remaining, it appears I am no longer capable of generating new keys. 

Relevant link to the discussions
https://github.com/toeverything/AFFiNE/discussions/6996#discussioncomment-9877437

**Comment by richie80** [comment]
Somewhere else I read they are doing an overhaul with the AI. Hopefully this is a quick fix and we don't have to wait for the AI improvements which are coming.

**Comment by tsic404** [comment]
https://github.com/toeverything/AFFiNE/issues/8905#issuecomment-2564683930

**Comment by richie80** [comment]
Seems to be fixed in the coming release. Great, eager to try it

**Comment by wtfbbqhax** [comment]
> Seems to be fixed in the coming release. Great, eager to try it

🤞🏻

**Comment by richie80** [comment]
confirming this is working again!

**Comment by forehalo** [comment]
fixed in 0.19.5, guys
